### ISSUE TITLE
panic when using wrong protocol against gateway port

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-server#1006]
- [x] Defect

To reproduce: 
 
```
$ echo '
"gateway": {
  "name": "do-lon1-kubecon-eu",
  "port": 4223,
}
' > conf/gateways.conf

# Run the server, then try to telnet and send:
# echo 'sub > 90' | nc 127.0.0.1 4223
# 
$ nats-server -c conf/gateways.conf 
[82250] 2019/05/22 09:15:29.094808 [INF] Starting nats-server version 2.0.0-RC12
[82250] 2019/05/22 09:15:29.094987 [INF] Git commit [not set]
[82250] 2019/05/22 09:15:29.095596 [INF] Gateway name is do-lon1-kubecon-eu
[82250] 2019/05/22 09:15:29.095781 [INF] Listening for gateways connections on 0.0.0.0:4223
[82250] 2019/05/22 09:15:29.096960 [INF] Address for gateway "do-lon1-kubecon-eu" is 172.16.48.18:4223
[82250] 2019/05/22 09:15:29.097596 [INF] Listening for client connections on 0.0.0.0:4222
[82250] 2019/05/22 09:15:29.097611 [INF] Server id is NADSGJ2DYU32GW3EFSIWA37KNYWFU4AFH6BBRGL3M4XHWY67FGYK2WUZ
[82250] 2019/05/22 09:15:29.097618 [INF] Server is ready
[82250] 2019/05/22 09:15:31.732195 [INF] 127.0.0.1:57115 - gid:1 - Processing inbound gateway connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1070ca6]

goroutine 22 [running]:
sync.(*Map).Load(0x0, 0x149aee0, 0xc000055d60, 0x1fc, 0x19264be, 0x1)
	/usr/local/Cellar/go/1.12/libexec/src/sync/map.go:103 +0x26
github.com/nats-io/nats-server/server.(*client).processGatewayRSub(0xc00022a000, 0xc000238204, 0x4, 0x1fc, 0x0, 0x0)
	/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/gateway.go:1716 +0x342
github.com/nats-io/nats-server/server.(*client).parse(0xc00022a000, 0xc000238200, 0xa, 0x200, 0xa, 0x0)
	/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/parser.go:405 +0x1acd
github.com/nats-io/nats-server/server.(*client).readLoop(0xc00022a000)
	/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/client.go:752 +0x1d5
github.com/nats-io/nats-server/server.(*Server).createGateway.func2()
	/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/gateway.go:737 +0x2a
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/nats-dev/src/github.com/nats-io/nats-server/server/server.go:1911 +0x91
```

**Comment by kozlovic** [comment]
Thanks, will look into that!

**Comment by derekcollison** [comment]
Do I owe Wally another signed $20?
