### ISSUE TITLE
Deadlock on authorization reload with service imports

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1544]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

nats-server: v2.2.0-beta.20

#### OS/Container environment:

ALL

#### Steps or code to reproduce the issue:

Config reload with routes and subscription on account with service imports.
Modified version of TestConfigReloadAccountServicesImportExport to include a route and a subscription to a specific subject. Will be updated in a coming PR.

#### Expected result:

No deadlock

#### Actual result:

Deadlock:
```
goroutine 20 [semacquire]:
sync.runtime_SemacquireMutex(0xc00028a034, 0x900000000, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00028a030)
	/usr/local/go/src/sync/mutex.go:138 +0x1c1
sync.(*Mutex).Lock(0xc00028a030)
	/usr/local/go/src/sync/mutex.go:81 +0x7d
github.com/nats-io/nats-server/server.(*Server).updateRouteSubscriptionMap(0xc00028a000, 0xc000288780, 0xc0000d0b00, 0xffffffff)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/route.go:1601 +0x504
github.com/nats-io/nats-server/server.(*client).processUnsub(0xc0002a2000, 0xc0000c689c, 0x1, 0x1, 0x0, 0x0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/client.go:2539 +0x37e
github.com/nats-io/nats-server/server.(*Account).removeAllServiceImportSubs(0xc000288780)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/accounts.go:1420 +0x478
github.com/nats-io/nats-server/server.(*Server).reloadAuthorization.func2(0x1b9ff80, 0xc0001ef270, 0x1c93100, 0xc0003585a0, 0xc00034a301)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload.go:1167 +0x55b
sync.(*Map).Range(0xc00028a240, 0xc000211058)
	/usr/local/go/src/sync/map.go:333 +0x156
github.com/nats-io/nats-server/server.(*Server).reloadAuthorization(0xc00028a000)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload.go:1133 +0xb95
github.com/nats-io/nats-server/server.(*Server).applyOptions(0xc00028a000, 0xc000211990, 0xc000310780, 0x2, 0x2)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload.go:1045 +0x20e
github.com/nats-io/nats-server/server.(*Server).reloadOptions(0xc00028a000, 0xc0000b7800, 0xc00034a000, 0x0, 0x0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload.go:728 +0x226
github.com/nats-io/nats-server/server.(*Server).Reload(0xc00028a000, 0x0, 0x0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload.go:669 +0x473
github.com/nats-io/nats-server/server.reloadUpdateConfig(0xc0000e30e0, 0xc00028a000, 0xc0000c8380, 0x3a, 0x1ceaf24, 0x230)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload_test.go:1638 +0x127
github.com/nats-io/nats-server/server.TestConfigReloadAccountServicesImportExport(0xc0000e30e0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/reload_test.go:3197 +0x113d
testing.tRunner(0xc0000e30e0, 0x1cf4800)
	/usr/local/go/src/testing/testing.go:991 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x661
```

**Comment by xieyuschen** [comment]
should be closed as solved.
