### ISSUE TITLE
JetStream: possible panic on consumer delete during server shutdown 

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-server#1621]
This would produce the following stack:
```
panic: close of closed channel

goroutine 2360 [running]:
github.com/nats-io/nats-server/v2/server.(*Consumer).stop(0xc0003c4e00, 0x10101, 0x0, 0x0)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/consumer.go:1722 +0xf5
github.com/nats-io/nats-server/v2/server.(*Consumer).Delete(...)
	/Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/consumer.go:1706
```

**Comment by derekcollison** [comment]
Thanks will take a look. Today is mostly mtgs through to like 2p..

**Comment by kozlovic** [comment]
I got this, will submit PR in a bit.
