### ISSUE TITLE
invalid memory address or nil pointer dereference: server/mqtt.go:3074

### ISSUE THREAD

**Issue by mullerch** [nats-io/nats-server#2265]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 Stack trace should be enough

#### Versions of `nats-server` and affected client libraries used:

nats-server v2.2.6

#### OS/Container environment:

nats:latest

#### Steps or code to reproduce the issue:

Not sure how to make that exhaustive, but main points of the config are

- Operator mode with full nats resolver
- Leaf node connected (the issue is not on the leafnode but on the main cluster server)
- Websocket enabled
- MQTT enabled
- JetStream enabled

```
port: 4222

monitor_port: 8222

jetstream {
  store_dir=nats
}

leafnodes {
  port: 7422
}

websocket {
  port: 4443
  no_tls: true
}

mqtt {
  port: 1883
}

operator: "/nats/config/operator.jwt"
resolver: {
  type: full
  dir: "/nats/accounts"
  allow_delete: false
}
```

#### Expected result:

Normal operation

#### Actual result:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a8e23]

goroutine 19443 [running]:
github.com/nats-io/nats-server/server.mqttDeliverMsgCbQos0(0xc000157c80, 0xc0002c4600, 0xc000141000, 0x35, 0x0, 0x0, 0xc0002c4859, 0xef, 0xfc7)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/mqtt.go:3074 +0x103
github.com/nats-io/nats-server/server.(*client).deliverMsg(0xc0002c4600, 0xc000157c80, 0xc0002c4820, 0x35, 0x1000, 0x0, 0x0, 0x0, 0xc0002c5a81, 0x52, ...)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:3072 +0xa6f
github.com/nats-io/nats-server/server.(*client).processMsgResults(0xc0002c4600, 0xc0002c8b40, 0xc0006be780, 0xc0002c4859, 0xf1, 0xfc7, 0x0, 0x0, 0x0, 0xc0002c4820, ...)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:4043 +0x5a5
github.com/nats-io/nats-server/server.(*client).processInboundLeafMsg(0xc0002c4600, 0xc0002c4859, 0xf1, 0xfc7)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/leafnode.go:2095 +0x278
github.com/nats-io/nats-server/server.(*client).processInboundMsg(0xc0002c4600, 0xc0002c4859, 0xf1, 0xfc7)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:3392 +0xcd
github.com/nats-io/nats-server/server.(*client).parse(0xc0002c4600, 0xc000663a00, 0x106, 0x200, 0x106, 0x0)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/parser.go:477 +0x2525
github.com/nats-io/nats-server/server.(*client).readLoop(0xc0002c4600, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:1160 +0x625
github.com/nats-io/nats-server/server.(*Server).createLeafNode.func1()
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/leafnode.go:921 +0x45
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2804 +0xc5
```

I guess this stack trace should be enough to find the issue. If not, let me know and I'll add details about the configuration.

**Comment by mullerch** [comment]
The issue typically occurs when a stream message is received from a leaf node and a MQTT client is connected. Message publisher and MQTT client use users from different account (with public export / import). The issue looks to occur 100% of the time.

**Comment by kozlovic** [comment]
@mullerch I want to create a test case for that since it clearly is a case that is not covered in our tests. The place it panics indicate that the subscription does not have the `mqtt` object associated with the subscription, which is strange since this callback is only associated with subscriptions that have this object.

Would you mind describing a bit more? The configuration that you added, I would assume is the one of the "cluster" NATS server. What is the leaf node config look like? Mind also sharing the configuration of the accounts being used? (you mentioned that this is cross accounts with export/imports).

I am not going to wait for you to provide above information in try to setup something to reproduce based on information I have so far, but would appreciate more details in case I can't reproduce. Thanks!

**Comment by mullerch** [comment]
Of course.

Here is an overview:

![overview](https://user-images.githubusercontent.com/1092115/121217053-c36d7900-c881-11eb-9d5f-efa8535bde9c.jpg)

**leaf-server**

The leaf server is a custom application integrating the nats server (go package). I don't think it's global configuration is helpful.

It connects as a leafnode by specifying:

```
		server.LeafNodeOpts{
			Remotes: []*server.RemoteLeafOpts{
				{
					URLs:        urls,
					Credentials: credentialsPath,
				},
			},
		}

```

**cluster-server**

```
# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

jetstream {
  store_dir=nats
}

leafnodes {
  port: 7422
}

websocket {
  port: 4443
  no_tls: true
}

mqtt {
  port: 1883
}

operator: "/nats/config/operator.jwt"
resolver: {
  type: full
  dir: "/nats/accounts"
  allow_delete: false
}
```


**device-account**

jwt
```
{
  "iat": 1623138321,
  "iss": "OBQJ6IOIN5J7VFOOIZT2ID22YGCFIEEVRN72L2RTWZXI4HTSBUH6TX6G",
  "jti": "HAIVFX54R5AV3GEPWR2ZQQC56HGULQLAC42PXBHAUA3LCQMQLNHQ",
  "name": "fcc23dfffe0a8c39",
  "sub": "ACYJ3HF27LN2I2HMTDMSKNK6F4UDZHUC5IGNNBSSQQLMCTBMRJGBBYJK",
  "nats": {
    "type": "account",
    "limits": {
      "subs": -1,
      "data": -1,
      "payload": -1,
      "imports": -1,
      "exports": -1,
      "wildcards": true,
      "conn": -1,
      "leaf": -1,
      "mem_storage": -1,
      "disk_storage": -1
    },
    "default_permissions": {},
    "exports": [
      {
        "name": "All getters",
        "subject": "get.>",
        "type": "service",
        "response_type": "Singleton",
        "token_req": false
      },
      {
        "name": "All setters",
        "subject": "set.>",
        "type": "service",
        "response_type": "Singleton",
        "token_req": false
      },
      {
        "name": "All calls",
        "subject": "call.>",
        "type": "service",
        "response_type": "Singleton",
        "token_req": false
      },
      {
        "name": "All events",
        "subject": "event.>",
        "type": "stream",
        "token_req": false
      }
    ],
    "account_type": "device",
    "version": 2
  }
}
```

**org-account**

```
{
  "iat": 1623138304,
  "iss": "OBQJ6IOIN5J7VFOOIZT2ID22YGCFIEEVRN72L2RTWZXI4HTSBUH6TX6G",
  "jti": "Y2UJNYQ5HTMNHQ3VLX575TDKBRQ2B5WGLRKMEKWFYGOKU77ATYJQ",
  "name": "acme",
  "sub": "ACNPB243QPED3ORXWZX7EQFF4ADUAI2BZA43HXH2SF3VIUD4XRR5XESU",
  "nats": {
    "type": "account",
    "limits": {
      "subs": -1,
      "data": -1,
      "payload": -1,
      "imports": -1,
      "exports": -1,
      "wildcards": true,
      "conn": -1,
      "leaf": -1,
      "mem_storage": -1,
      "disk_storage": -1
    },
    "default_permissions": {},
    "imports": [
      {
        "name": "fcc23dfffe0a8c39 getters",
        "subject": "get.>",
        "account": "ACYJ3HF27LN2I2HMTDMSKNK6F4UDZHUC5IGNNBSSQQLMCTBMRJGBBYJK",
        "local_subject": "fcc23dfffe0a8c39.get.>",
        "type": "service"
      },
      {
        "name": "fcc23dfffe0a8c39 setters",
        "subject": "set.>",
        "account": "ACYJ3HF27LN2I2HMTDMSKNK6F4UDZHUC5IGNNBSSQQLMCTBMRJGBBYJK",
        "local_subject": "fcc23dfffe0a8c39.set.>",
        "type": "service"
      },
      {
        "name": "fcc23dfffe0a8c39 calls",
        "subject": "call.>",
        "account": "ACYJ3HF27LN2I2HMTDMSKNK6F4UDZHUC5IGNNBSSQQLMCTBMRJGBBYJK",
        "local_subject": "fcc23dfffe0a8c39.call.>",
        "type": "service"
      },
      {
        "name": "fcc23dfffe0a8c39 events",
        "subject": "event.>",
        "account": "ACYJ3HF27LN2I2HMTDMSKNK6F4UDZHUC5IGNNBSSQQLMCTBMRJGBBYJK",
        "local_subject": "fcc23dfffe0a8c39.event.>",
        "type": "stream"
      }
    ],
    "account_type": "organization",
    "version": 2
  }
}
```

**Comment by kozlovic** [comment]
@mullerch For your information, I have been able to reproduce and I am working on a fix. Thanks!
