### ISSUE TITLE
panic when nats update a non-exists Stream

### ISSUE THREAD

**Issue by zhaojizhuang** [nats-io/nats-server#2283]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
```bash
[32] 2021/05/31 01:53:19.717553 [INF] Starting nats-server version 2.2.0-beta.15
[32] 2021/05/31 01:53:19.717604 [DBG] Go build version go1.14.4
[32] 2021/05/31 01:53:19.717608 [INF] Git commit [ddfbc33c]
[32] 2021/05/31 01:53:19.717644 [DBG] Created system account: "$SYS"
[32] 2021/05/31 01:53:19.718098 [FTL] Error listening on port: 0.0.0.0:4222, "listen tcp 0.0.0.0:4222: bind: address already in use"
``` 
- [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Steps or code to reproduce the issue:

1. Run a server using `docker`:`docker run -ti -p 4222:4222 --name jetstream synadia/jsm:latest server`

```bash
[root@k8s-master ~]# docker run -ti -p 4222:4222 --name jetstream synadia/jsm:latest server
[1] 2021/05/31 01:51:54.282433 [INF] Starting nats-server version 2.2.0-beta.15
[1] 2021/05/31 01:51:54.282481 [INF] Git commit [ddfbc33c]
[1] 2021/05/31 01:51:54.282665 [INF] Starting JetStream
[1] 2021/05/31 01:51:54.282949 [WRN]     _ ___ _____ ___ _____ ___ ___   _   __  __
[1] 2021/05/31 01:51:54.282958 [WRN]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[1] 2021/05/31 01:51:54.282963 [WRN] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[1] 2021/05/31 01:51:54.282968 [WRN]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[1] 2021/05/31 01:51:54.282970 [WRN]
[1] 2021/05/31 01:51:54.282973 [WRN]                _         _
[1] 2021/05/31 01:51:54.282975 [WRN]               | |__  ___| |_ __ _
[1] 2021/05/31 01:51:54.282977 [WRN]               | '_ \/ -_)  _/ _` |
[1] 2021/05/31 01:51:54.282979 [WRN]               |_.__/\___|\__\__,_|
[1] 2021/05/31 01:51:54.282982 [WRN]
[1] 2021/05/31 01:51:54.282984 [WRN]          JetStream is a Beta feature
[1] 2021/05/31 01:51:54.282986 [WRN]     https://github.com/nats-io/jetstream
[1] 2021/05/31 01:51:54.282988 [INF]
[1] 2021/05/31 01:51:54.282990 [INF] ----------- JETSTREAM -----------
[1] 2021/05/31 01:51:54.282995 [INF]   Max Memory:      6.47 GB
[1] 2021/05/31 01:51:54.282999 [INF]   Max Storage:     1.00 TB
[1] 2021/05/31 01:51:54.283003 [INF]   Store Directory: "/tmp/nats-jetstream-storedir-542975544/jetstream"
[1] 2021/05/31 01:51:54.283034 [INF] ----------------------------------------
[1] 2021/05/31 01:51:54.283124 [INF]   Upgrading storage directory structure for "$G"
[1] 2021/05/31 01:51:54.283179 [INF]   Recovering JetStream state for account "$G"
[1] 2021/05/31 01:51:54.283229 [INF] JetStream state for account "$G" recovered
[1] 2021/05/31 01:51:54.283389 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2021/05/31 01:51:54.283538 [INF] Server id is NBLPNL3LGR7AESY3NQIEDCR73ZXQIAVWD647FX4ATKYY6OUXCYSM2EBM
[1] 2021/05/31 01:51:54.283546 [INF] Server is ready
```

2. Update a non-existent stream，as follows: `K-ORDERS` wasn't created before
```go
	js.UpdateStream(&nats.StreamConfig{
		Name:     "K-ORDERS",
		Subjects: []string{"K-ORDERS.*"},
	})
```

#### Actual result:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d2067]

goroutine 5178 [running]:
github.com/nats-io/nats-server/server.(*Stream).Config(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/nats-io/nats-server/server/stream.go:343 +0x57
github.com/nats-io/nats-server/server.(*Stream).Update(0x0, 0xc0000ec900, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-server/server/stream.go:369 +0x13e
github.com/nats-io/nats-server/server.(*Server).jsStreamUpdateRequest(0xc0000cc000, 0xc0001763f0, 0xc000269980, 0xc000021e20, 0x1e, 0xc00022ab40, 0x26, 0xc000372a77, 0xad, 0x189)
	/go/src/github.com/nats-io/nats-server/server/jetstream_api.go:802 +0x5cb
github.com/nats-io/nats-server/server.(*client).deliverMsg(0xc000269980, 0xc0001763f0, 0xc0001ad250, 0x1e, 0x20, 0xc000269c71, 0x3d, 0x3ff, 0xc000372a77, 0xaf, ...)
	/go/src/github.com/nats-io/nats-server/server/client.go:2754 +0x321
github.com/nats-io/nats-server/server.(*client).processMsgResults(0xc000269980, 0xc00000a1e0, 0xc000097b30, 0xc000372a77, 0xaf, 0x189, 0x0, 0x0, 0x0, 0xc000345250, ...)
	/go/src/github.com/nats-io/nats-server/server/client.go:3460 +0x570
github.com/nats-io/nats-server/server.(*client).processServiceImport(0xc000269980, 0xc000146600, 0xc0000ea000, 0xc000372a77, 0xaf, 0x189)
	/go/src/github.com/nats-io/nats-server/server/client.go:3309 +0x6fe
github.com/nats-io/nats-server/server.(*Account).addServiceImportSub.func1(0xc000177d40, 0xc000269980, 0xc000021da0, 0x1e, 0xc00022aab0, 0x26, 0xc000372a77, 0xaf, 0x189)
	/go/src/github.com/nats-io/nats-server/server/accounts.go:1387 +0x5e
github.com/nats-io/nats-server/server.(*client).deliverMsg(0xc000269980, 0xc000177d40, 0xc000372a2c, 0x1e, 0x1d4, 0xc000269c71, 0x51, 0x3ff, 0xc000372a77, 0xaf, ...)
	/go/src/github.com/nats-io/nats-server/server/client.go:2752 +0x433
github.com/nats-io/nats-server/server.(*client).processMsgResults(0xc000269980, 0xc0000ea000, 0xc000097b00, 0xc000372a77, 0xaf, 0x189, 0x0, 0x0, 0x0, 0xc000372a2c, ...)
	/go/src/github.com/nats-io/nats-server/server/client.go:3460 +0x570
github.com/nats-io/nats-server/server.(*client).processInboundClientMsg(0xc000269980, 0xc000372a77, 0xaf, 0x189, 0x18e)
	/go/src/github.com/nats-io/nats-server/server/client.go:3159 +0x3c8
github.com/nats-io/nats-server/server.(*client).processInboundMsg(0xc000269980, 0xc000372a77, 0xaf, 0x189)
	/go/src/github.com/nats-io/nats-server/server/client.go:3040 +0x95
github.com/nats-io/nats-server/server.(*client).parse(0xc000269980, 0xc000372a00, 0x126, 0x200, 0x126, 0x0)
	/go/src/github.com/nats-io/nats-server/server/parser.go:441 +0x212b
github.com/nats-io/nats-server/server.(*client).readLoop(0xc000269980, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-server/server/client.go:956 +0x4fc
github.com/nats-io/nats-server/server.(*Server).createClient.func2()
	/go/src/github.com/nats-io/nats-server/server/server.go:2045 +0x45
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/go/src/github.com/nats-io/nats-server/server/server.go:2422 +0xad
```

**Comment by derekcollison** [comment]
The nightly is now at 2.3.0-beta.8.

Could you test that version and let us know if this is still an issue? Seems you were testing a pre-release version that is pretty old at this point.

**Comment by zhaojizhuang** [comment]
> The nightly is now at 2.3.0-beta.8.
> 
> Could you test that version and let us know if this is still an issue? Seems you were testing a pre-release version that is pretty old at this point.

@derekcollison the latest version works well, this issue was gone
