### ISSUE TITLE
Wrong bodies sent in response to MSG.NEXT in pull consumer with subject filtering

### ISSUE THREAD

**Issue by trown** [nats-io/nats-server#2372]
# Wrong bodies sent in response to MSG.NEXT in pull consumer with subject filtering
We have a large (>300k messages) stream with a uniform-ish mix of fairly large (several kb) and small (<0.5 kb) messages with json content.

We have a setup where about 80-100 clients use 3-5 pull consumers with subject filtering each consuming messages at about 0.2-1 messages per second from such stream. All subjects in each consumer are disjoint. AckWait timeouts are very generous (>30m). These consumers perform aggregation and publish their results to another stream with acknowledgements.
After several minutes of operation we started noticing JSON parse failures when processing arrived messages in our python asyncio client.

By adding client-side protocol logging to the client we caught nats-server sending wrong bodies that look like a memory dump of some other stream or a different location within a stream.
```
Jul 21 15:35:49 reconciler-787868d4d8-mzczh zenai DEBUG 1 | zenai.nats.parser:parse:82 - data=b'MSG
utterances.60f83071ea9824001316eddb 353 $JS.ACK.utterances.60f83071ea9824001316eddb-reconcilera.1.1889278.123.1626881494539443733.163
212\r\nt", "start": 134.82, "end": 134.969941, "conf": 0.994307},
{"case": "success", "startOffset": 119, "endOffset": 132, "word": "vulnerability", "alignedWord": "vulnerability", "start": 134.970146, "end": 135.84, "c\r\n'
```

If we query the message by id observed in the reply-to field on the MSG above we get a correct response with the same body length:
```log
str get utterances  1889278
Item: utterances#1889278 received 2021-07-21 15:31:34.539443733 +0000 UTC on Subject utterances.60f83071ea9824001316eddb
{"upload_key": "5fd0b2317763711b5b63516a/common-biggest-mistakes-made-by-amazon-sellers/recording-1/2021-07-21--t02-34-25pm--helen510--helen.mp3", "silence": true, "start": 622.65, "end": 627.69, "conf": 0.96323}
```

In some cases we observed random binary junk padding message bodies.

We also observed some null pointer dereferences during operation: 
```
Jul 21 17:20:53 nats-js-0 nats 2021/07/21 21:20:53 http: panic serving 10.240.0.163:58538: runtime error: invalid memory address or nil pointer dereference
Jul 21 17:20:53 nats-js-0 nats goroutine 16829622 [running]:
Jul 21 17:20:53 nats-js-0 nats net/http.(*conn).serve.func1(0xc000138140)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:1824 +0x153
Jul 21 17:20:53 nats-js-0 nats panic(0xa291e0, 0xe895d0)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/runtime/panic.go:971 +0x499
Jul 21 17:20:53 nats-js-0 nats github.com/nats-io/nats-server/server.(*Server).accountDetail(0xc00015a000, 0xc000220000, 0x101, 0xc002f0e168)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2349 +0x68a
Jul 21 17:20:53 nats-js-0 nats github.com/nats-io/nats-server/server.(*Server).Jsz(0xc00015a000, 0xc008117a80, 0xad6cd5, 0x3, 0xec8de0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2494 +0x7e6
Jul 21 17:20:53 nats-js-0 nats github.com/nats-io/nats-server/server.(*Server).HandleJsz(0xc00015a000, 0xba08c0, 0xc000540000, 0xc0068f4100)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2534 +0x3d8
Jul 21 17:20:53 nats-js-0 nats net/http.HandlerFunc.ServeHTTP(0xc00005f240, 0xba08c0, 0xc000540000, 0xc0068f4100)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2069 +0x44
Jul 21 17:20:53 nats-js-0 nats net/http.(*ServeMux).ServeHTTP(0xc0004c64c0, 0xba08c0, 0xc000540000, 0xc0068f4100)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2448 +0x1ad
Jul 21 17:20:53 nats-js-0 nats net/http.serverHandler.ServeHTTP(0xc00073aa80, 0xba08c0, 0xc000540000, 0xc0068f4100)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:2887 +0xa3
Jul 21 17:20:53 nats-js-0 nats net/http.(*conn).serve(0xc000138140, 0xba2768, 0xc004ad2100)
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:1952 +0x8cd
Jul 21 17:20:53 nats-js-0 nats created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.16.5.linux.amd64/src/net/http/server.go:3013 +0x39b
```
nats version: 2.3.1
python client version: asyncio-nats-client 0.11.4
jetstream is configured as a leaf node to a HA NATS setup on k8s:
```
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222

    jetstream {
      store_dir: "/data/jetstream/store"
      max_file_store: 100G
    }

    leafnodes {
      remotes [
        {
          url: "nats://nats:7422"
        }
      ]
    }
```

**Comment by derekcollison** [comment]
This is a known issue and is fixed in the latest release of the software. Your data and messages on disk are ok, so just upgrading the server should resolve.
