### ISSUE TITLE
Placed an entry at the wrong index

### ISSUE THREAD

**Issue by mikluko** [nats-io/nats-server#2391]
#### Versions of `nats-server` and affected client libraries used:

NATS Server v2.3.2, deployed by Helm chart v0.8.4

#### OS/Container environment:

RKE 1.2.9, Kubernetes 1.2.80, Docker 20.10.7

#### Steps or code to reproduce the issue:

It's a 5-node cluster. The cluster was under use for quite some time before it was restarted with `kubectl rollout restart statefulset/nats`.

#### Expected result:

All cluster pods restarted one by one, in the rolling manner.

#### Actual result:

4 out of 5 pods restart successfully. One goes into crash cycle with the following logging output tail: 

```
[83] 2021/07/31 07:45:33.165840 [DBG] RAFT [cnrtt3eg - C-R3F-er29H0Re] Update peers from leader to map[bkCGheKT:0xc0005ce100 cnrtt3eg:0xc00013f120 yrzKKRBu:0xc0005ce0f0]
panic: [nats-2-S-R3F-VkruMIMt] Placed an entry at the wrong index, ae is &{leader:yrzKKRBu term:34 commit:208 pterm:34 pindex:208 entries: 1}, seq is 218, n.pindex is 208



goroutine 154 [running]:
github.com/nats-io/nats-server/server.(*raft).storeToWAL(0xc000b44000, 0xc07fab7100, 0xe99920, 0x8)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2774 +0x357
github.com/nats-io/nats-server/server.(*raft).processAppendEntry(0xc000b44000, 0xc07fab7100, 0xc08e06a0c0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2636 +0x8c5
github.com/nats-io/nats-server/server.(*raft).runAsFollower(0xc000b44000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1464 +0x1ce
github.com/nats-io/nats-server/server.(*raft).run(0xc000b44000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1416 +0xed
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2827 +0xc5



goroutine 154 [running]:
github.com/nats-io/nats-server/server.(*raft).storeToWAL(0xc000b44000, 0xc07fab7100, 0xe99920, 0x8)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2774 +0x357
github.com/nats-io/nats-server/server.(*raft).processAppendEntry(0xc000b44000, 0xc07fab7100, 0xc08e06a0c0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2636 +0x8c5
github.com/nats-io/nats-server/server.(*raft).runAsFollower(0xc000b44000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1464 +0x1ce
github.com/nats-io/nats-server/server.(*raft).run(0xc000b44000)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1416 +0xed
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2827 +0xc5
```

[Full log](https://github.com/nats-io/nats-server/files/6910864/nats-2.log)

**Comment by derekcollison** [comment]
Thanks, would it be possible to privately send us the complete storage directory for each server?

**Comment by carr123** [comment]
i encounter the same problem today.
i made thousands of MQTT connections to nats cluster, minutes later one node crashed.
then i restart the crashed node, i notice it takes too long(more than 60 seconds) to listen on TCP PORT 4222, 8222, 1833 after the process started.
i stopped testing.  no heavy workload any more. only a few nats requests other programs made.
a few minutes later, another node crashed.

it seems something wrong with the raft logic.

here is the log:

panic: [server226-S-R2F-ziqQhGPV] Placed an entry at the wrong index, ae is &{leader:1txmfIKU term:184 commit:0 pterm:0 pindex:0 entries: 1}, seq is 4, n.pindex is 0


goroutine 14561 [running]:
github.com/nats-io/nats-server/server.(*raft).storeToWAL(0xc000dee2c0, 0xc00673ce80, 0xf, 0xc0364cca40)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2774 +0x357
github.com/nats-io/nats-server/server.(*raft).processAppendEntry(0xc000dee2c0, 0xc00673ce80, 0xc0066c26c0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2636 +0x8c5
github.com/nats-io/nats-server/server.(*raft).runAsFollower(0xc000dee2c0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1464 +0x1ce
github.com/nats-io/nats-server/server.(*raft).run(0xc000dee2c0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1416 +0xed
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2839 +0xc5

**Comment by derekcollison** [comment]
Any other details on what led up to the first crash? This is a forced panic since in our code due to state corruption. Were you killing terminals on windows in this test as well?

**Comment by carr123** [comment]
this is on Ubuntu18.04，3 nodes cluster on 3  machines，i was testing mqtt connection pressure，i didn't close any node on purpose before the panic happen。i am not sure what led to the  first crash，maybe too frequent MQTT connection，maybe the raft state got messed。
the crashed node received about 5000 TCP connections before it crashed。
then another node fail to receive more TCP connections although it didn't crash。
the last node continue runs well，it can accept 15K connections before i stop the test。

**Comment by derekcollison** [comment]
And server version 2.4.0 correct?

**Comment by carr123** [comment]
yes, linux amd64 server version 2.4.0
----- 原始邮件 -----
发件人：Derek Collison ***@***.***>
收件人：nats-io/nats-server ***@***.***>
抄送人：carr123 ***@***.***>,  Comment ***@***.***>
主题：Re: [nats-io/nats-server] Placed an entry at the wrong index (#2391)
日期：2021年09月01日 22点35分


And server version 2.4.0 correct?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by derekcollison** [comment]
Thanks.

**Comment by carr123** [comment]
maybe after the last issue i reported fixed，this one could disappear as well.
I will test it again after new server version come out.
thanks to your efforts.

**Comment by carr123** [comment]
@derekcollison  i leave office, no testing clients running. 12 hours later, i came back, one node crashed.
this time the panic log is different, it worth a look.  you can download from http://101.200.84.208/nohup.txt
this download link expires in 3 days.

**Comment by derekcollison** [comment]
Seems the system you are running on has a hard limit of 1000 threads. That is at the top there. What system is this on?

**Comment by derekcollison** [comment]
How many consumers were you trying to create?

**Comment by derekcollison** [comment]
And how many streams? Seems quite a very large amount of both..

**Comment by derekcollison** [comment]
What does the nats cli report via the following?

```nats stream report```

**Comment by kozlovic** [comment]
@derekcollison If the question is to @carr123, the report says that many MQTT connections were created. As you know, each MQTT session will have its own stream (max msgs of 1), so that may explain the number of streams that you are seeing?

**Comment by carr123** [comment]
ubuntu18.04,  amd64
not 1000 but 10,000 threads. (is this OS threads ? if it is, seems too many for a single process)

i tested mqtt connection 12 hours ago, there are 5327 folders there under jetstream directory, it seems one folder for one connection. each folder named like $MQTT_sess_zlNVCJTT

nats stream report  results:   http://101.200.84.208/stream.txt

**Comment by carr123** [comment]
i restart the crashed node  server227, and find its threads grows slowly from less than 10 to near 200. and continue to grow.

http://101.200.84.208/threads.png

**Comment by carr123** [comment]
server227 threads grow up to 428 and stop growing. but server226 begin to crash.
i noticed this yestoday, server226 and server 227 take turns to crash. another node server225 is alway healthy.

server226 panic log:
panic: [server226-S-R2F-TM5kP7eZ] Placed an entry at the wrong index, ae is &{leader:1txmfIKU term:182 commit:0 pterm:179 pindex:2 entries: 1}, seq is 5, n.pindex is 2

goroutine 21454 [running]:
github.com/nats-io/nats-server/server.(*raft).storeToWAL(0xc00a48d080, 0xc36268c080, 0xf, 0xc36e659fa0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2774 +0x357
github.com/nats-io/nats-server/server.(*raft).processAppendEntry(0xc00a48d080, 0xc36268c080, 0xc16002fbc0)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:2636 +0x8c5
github.com/nats-io/nats-server/server.(*raft).runAsFollower(0xc00a48d080)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1464 +0x1ce
github.com/nats-io/nats-server/server.(*raft).run(0xc00a48d080)
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/raft.go:1416 +0xed
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
	/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2839 +0xc5



hope those logs can give you some clue.

**Comment by carr123** [comment]
after server226 crashed, i restart it, watch its threads.  
thread num grow up to 2084 on server226,  then server227 crash again.
this is captured on server226 : http://101.200.84.208/thread226.png
maybe you should restrict the thread num one process can create.

**Comment by carr123** [comment]
OK, thanks.  
in my opinion, golang program can start many goroutines other than many threads.
context switching between threads do harm to sytems performance.

**Comment by derekcollison** [comment]
Currently a MQTT connection has its own stream per connection which again we can now update and improve by using the K/V functionality of JetStream to mux 1 stream for all MQTT clients on a server. This work is being prioritized.

**Comment by carr123** [comment]
Great, i won't test against mqtt until it's improved.

**Comment by derekcollison** [comment]
Will keep you posted. Thanks.

**Comment by carr123** [comment]
@derekcollison hello, first congratulations for nats-server release v2.5.0.
i test mqtt againt nats-server 2.5.0 linux-amd64.  (i build my own binary)
i made 1000 mqtt client connections
1. notice there are 1001 subdirectories under $MQTT_msgs/obs/, i doubt if i made 100K connections, whether the folder count will exceed linux limits.
2. also notice there are too many(7046) goroutines, maybe they cost too much RAM space.
  the file writer and raft logic takes many goroutines. i'm not sure if these code could be optimized.
3. sometimes, clients connection fail ("Connecting to tcp://10.91.26.226:1883 CONNACK was not CONN_ACCEPTED, but rather Connection Error"), then subdirectory count under $MQTT_msgs/obs/ still increase, the goroutine count increase accordingly.
and these folder are never deleted even after server restart.

you mentioned "mux 1 stream for all MQTT clients on a server", the sessions are now  indeed merged into a single $MQTT_sess folder. i wonder whether the obs subfolders could be merged  then goroutines and memory usage are saved.

thanks.

below are logs from http/pprof


goroutine profile: total 7046
1004 @ 0x437a96 0x447832 0x89f87c 0x467ba1
#	0x89f87b	github.com/nats-io/nats-server/v2/server.(*raft).fileWriter+0x25b	D:/project/src/github.com/nats-io/nats-server/server/raft.go:3002

1001 @ 0x437a96 0x447832 0x7a7cb9 0x467ba1
#	0x7a7cb8	github.com/nats-io/nats-server/v2/server.(*consumerFileStore).flushLoop+0x1b8	D:/project/src/github.com/nats-io/nats-server/server/filestore.go:4721

1001 @ 0x437a96 0x447832 0x7fe656 0x7fd305 0x467ba1
#	0x7fe655	github.com/nats-io/nats-server/v2/server.(*jetStream).monitorConsumer+0x4f5			D:/project/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2861
#	0x7fd304	github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateConsumer.func1+0x24	D:/project/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2691

1000 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b5e9a 0x4b5e88 0x5718a9 0x57d4c5 0x752427 0x840da9 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88						c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31						c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b5e99	internal/poll.(*pollDesc).waitRead+0x259					c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b5e87	internal/poll.(*FD).Read+0x247							c:/go/src/internal/poll/fd_unix.go:167
#	0x5718a8	net.(*netFD).Read+0x28								c:/go/src/net/fd_posix.go:56
#	0x57d4c4	net.(*conn).Read+0x44								c:/go/src/net/net.go:183
#	0x752426	github.com/nats-io/nats-server/v2/server.(*client).readLoop+0x5a6		D:/project/src/github.com/nats-io/nats-server/server/client.go:1134
#	0x840da8	github.com/nats-io/nats-server/v2/server.(*Server).createMQTTClient.func1+0x28	D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:515

1000 @ 0x437a96 0x463e9d 0x463e7d 0x478cac 0x7519b5 0x840d5d 0x467ba1
#	0x463e7c	sync.runtime_notifyListWait+0x11c						c:/go/src/runtime/sema.go:513
#	0x478cab	sync.(*Cond).Wait+0x8b								c:/go/src/sync/cond.go:56
#	0x7519b4	github.com/nats-io/nats-server/v2/server.(*client).writeLoop+0x1f4		D:/project/src/github.com/nats-io/nats-server/server/client.go:997
#	0x840d5c	github.com/nats-io/nats-server/v2/server.(*Server).createMQTTClient.func2+0x1c	D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:516

506 @ 0x437a96 0x447832 0x897105 0x894d91 0x467ba1
#	0x897104	github.com/nats-io/nats-server/v2/server.(*raft).runAsLeader+0x5a4	D:/project/src/github.com/nats-io/nats-server/server/raft.go:1744
#	0x894d90	github.com/nats-io/nats-server/v2/server.(*raft).run+0xd0		D:/project/src/github.com/nats-io/nats-server/server/raft.go:1420

505 @ 0x437a96 0x447832 0x771851 0x467ba1
#	0x771850	github.com/nats-io/nats-server/v2/server.(*consumer).loopAndForwardProposals+0x170	D:/project/src/github.com/nats-io/nats-server/server/consumer.go:1273

505 @ 0x437a96 0x447832 0x776549 0x467ba1
#	0x776548	github.com/nats-io/nats-server/v2/server.(*consumer).loopAndGatherMsgs+0x448	D:/project/src/github.com/nats-io/nats-server/server/consumer.go:2260

498 @ 0x437a96 0x447832 0x8956aa 0x894d85 0x467ba1
#	0x8956a9	github.com/nats-io/nats-server/v2/server.(*raft).runAsFollower+0x129	D:/project/src/github.com/nats-io/nats-server/server/raft.go:1462
#	0x894d84	github.com/nats-io/nats-server/v2/server.(*raft).run+0xc4		D:/project/src/github.com/nats-io/nats-server/server/raft.go:1416

3 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b6d8c 0x4b6d79 0x572a75 0x586da8 0x5860dd 0x8c6909 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88						c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31						c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b6d8b	internal/poll.(*pollDesc).waitRead+0x22b					c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b6d78	internal/poll.(*FD).Accept+0x218						c:/go/src/internal/poll/fd_unix.go:402
#	0x572a74	net.(*netFD).accept+0x34							c:/go/src/net/fd_unix.go:173
#	0x586da7	net.(*TCPListener).accept+0x27							c:/go/src/net/tcpsock_posix.go:140
#	0x5860dc	net.(*TCPListener).Accept+0x3c							c:/go/src/net/tcpsock.go:262
#	0x8c6908	github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections+0x68	D:/project/src/github.com/nats-io/nats-server/server/server.go:2007

2 @ 0x437a96 0x447832 0x7f2b0f 0x7fabe8 0x467ba1
#	0x7f2b0e	github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream+0xa0e			D:/project/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:1439
#	0x7fabe7	github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1+0x27	D:/project/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2290

2 @ 0x437a96 0x447832 0x8e318b 0x467ba1
#	0x8e318a	github.com/nats-io/nats-server/v2/server.(*stream).internalLoop+0x22a	D:/project/src/github.com/nats-io/nats-server/server/stream.go:3006

2 @ 0x437a96 0x463e9d 0x463e7d 0x478cac 0x7519b5 0x8b7a9d 0x467ba1
#	0x463e7c	sync.runtime_notifyListWait+0x11c						c:/go/src/runtime/sema.go:513
#	0x478cab	sync.(*Cond).Wait+0x8b								c:/go/src/sync/cond.go:56
#	0x7519b4	github.com/nats-io/nats-server/v2/server.(*client).writeLoop+0x1f4		D:/project/src/github.com/nats-io/nats-server/server/client.go:997
#	0x8b7a9c	github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func2+0x1c	D:/project/src/github.com/nats-io/nats-server/server/route.go:1378

1 @ 0x40b734 0x464378 0x72e0f9 0x467ba1
#	0x464377	os/signal.signal_recv+0x97	c:/go/src/runtime/sigqueue.go:169
#	0x72e0f8	os/signal.loop+0x18		c:/go/src/os/signal/signal_unix.go:24

1 @ 0x437a96 0x40630c 0x405d38 0x918d0e 0x918cfb 0x4376c7 0x467ba1
#	0x918d0d	github.com/nats-io/nats-server/v2/server.(*Server).WaitForShutdown+0x32d	D:/project/src/github.com/nats-io/nats-server/server/server.go:1926
#	0x918cfa	main.main+0x31a									D:/project/src/github.com/nats-io/nats-server/main.go:128
#	0x4376c6	runtime.main+0x226								c:/go/src/runtime/proc.go:255

1 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b5e9a 0x4b5e88 0x5718a9 0x57d4c5 0x64d32d 0x536043 0x536bef 0x536e47 0x5ea999 0x6493b9 0x6493ba 0x64e6e5 0x6529a5 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88		c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31		c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b5e99	internal/poll.(*pollDesc).waitRead+0x259	c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b5e87	internal/poll.(*FD).Read+0x247			c:/go/src/internal/poll/fd_unix.go:167
#	0x5718a8	net.(*netFD).Read+0x28				c:/go/src/net/fd_posix.go:56
#	0x57d4c4	net.(*conn).Read+0x44				c:/go/src/net/net.go:183
#	0x64d32c	net/http.(*connReader).Read+0x16c		c:/go/src/net/http/server.go:780
#	0x536042	bufio.(*Reader).fill+0x102			c:/go/src/bufio/bufio.go:101
#	0x536bee	bufio.(*Reader).ReadSlice+0x2e			c:/go/src/bufio/bufio.go:360
#	0x536e46	bufio.(*Reader).ReadLine+0x26			c:/go/src/bufio/bufio.go:389
#	0x5ea998	net/textproto.(*Reader).readLineSlice+0x98	c:/go/src/net/textproto/reader.go:57
#	0x6493b8	net/textproto.(*Reader).ReadLine+0x78		c:/go/src/net/textproto/reader.go:38
#	0x6493b9	net/http.readRequest+0x79			c:/go/src/net/http/request.go:1029
#	0x64e6e4	net/http.(*conn).readRequest+0x224		c:/go/src/net/http/server.go:966
#	0x6529a4	net/http.(*conn).serve+0x864			c:/go/src/net/http/server.go:1855

1 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b5e9a 0x4b5e88 0x5718a9 0x57d4c5 0x752427 0x8b7ae5 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88						c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31						c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b5e99	internal/poll.(*pollDesc).waitRead+0x259					c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b5e87	internal/poll.(*FD).Read+0x247							c:/go/src/internal/poll/fd_unix.go:167
#	0x5718a8	net.(*netFD).Read+0x28								c:/go/src/net/fd_posix.go:56
#	0x57d4c4	net.(*conn).Read+0x44								c:/go/src/net/net.go:183
#	0x752426	github.com/nats-io/nats-server/v2/server.(*client).readLoop+0x5a6		D:/project/src/github.com/nats-io/nats-server/server/client.go:1134
#	0x8b7ae4	github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func1+0x24	D:/project/src/github.com/nats-io/nats-server/server/route.go:1375

1 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b6d8c 0x4b6d79 0x572a75 0x586da8 0x5860dd 0x656cb4 0x6568dd 0x918f4a 0x918f4b 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88		c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31		c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b6d8b	internal/poll.(*pollDesc).waitRead+0x22b	c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b6d78	internal/poll.(*FD).Accept+0x218		c:/go/src/internal/poll/fd_unix.go:402
#	0x572a74	net.(*netFD).accept+0x34			c:/go/src/net/fd_unix.go:173
#	0x586da7	net.(*TCPListener).accept+0x27			c:/go/src/net/tcpsock_posix.go:140
#	0x5860dc	net.(*TCPListener).Accept+0x3c			c:/go/src/net/tcpsock.go:262
#	0x656cb3	net/http.(*Server).Serve+0x393			c:/go/src/net/http/server.go:3001
#	0x6568dc	net/http.(*Server).ListenAndServe+0x7c		c:/go/src/net/http/server.go:2930
#	0x918f49	net/http.ListenAndServe+0x109			c:/go/src/net/http/server.go:3184
#	0x918f4a	main.http_pprof+0x10a				D:/project/src/github.com/nats-io/nats-server/main.go:145

1 @ 0x437a96 0x43043e 0x462509 0x4b4f32 0x4b6d8c 0x4b6d79 0x572a75 0x586da8 0x5860dd 0x656cb4 0x8c8817 0x467ba1
#	0x462508	internal/poll.runtime_pollWait+0x88						c:/go/src/runtime/netpoll.go:229
#	0x4b4f31	internal/poll.(*pollDesc).wait+0x31						c:/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4b6d8b	internal/poll.(*pollDesc).waitRead+0x22b					c:/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4b6d78	internal/poll.(*FD).Accept+0x218						c:/go/src/internal/poll/fd_unix.go:402
#	0x572a74	net.(*netFD).accept+0x34							c:/go/src/net/fd_unix.go:173
#	0x586da7	net.(*TCPListener).accept+0x27							c:/go/src/net/tcpsock_posix.go:140
#	0x5860dc	net.(*TCPListener).Accept+0x3c							c:/go/src/net/tcpsock.go:262
#	0x656cb3	net/http.(*Server).Serve+0x393							c:/go/src/net/http/server.go:3001
#	0x8c8816	github.com/nats-io/nats-server/v2/server.(*Server).startMonitoring.func1+0x56	D:/project/src/github.com/nats-io/nats-server/server/server.go:2243

1 @ 0x437a96 0x447832 0x780206 0x467ba1
#	0x780205	github.com/nats-io/nats-server/v2/server.(*Server).internalSendLoop+0x385	D:/project/src/github.com/nats-io/nats-server/server/events.go:300

1 @ 0x437a96 0x447832 0x7bf93e 0x467ba1
#	0x7bf93d	github.com/nats-io/nats-server/v2/server.(*Server).startGWReplyMapExpiration.func1+0x11d	D:/project/src/github.com/nats-io/nats-server/server/gateway.go:3130

1 @ 0x437a96 0x447832 0x7ecb56 0x467ba1
#	0x7ecb55	github.com/nats-io/nats-server/v2/server.(*jetStream).monitorCluster+0x355	D:/project/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:747

1 @ 0x437a96 0x447832 0x84788b 0x8445e9 0x467ba1
#	0x84788a	github.com/nats-io/nats-server/v2/server.(*mqttAccountSessionManager).sessPersistProcessing+0x10a	D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:1505
#	0x8445e8	github.com/nats-io/nats-server/v2/server.(*Server).mqttCreateAccountSessionManager.func3+0x68		D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:1001

1 @ 0x437a96 0x447832 0x848431 0x8446f5 0x467ba1
#	0x848430	github.com/nats-io/nats-server/v2/server.(*mqttAccountSessionManager).sendJSAPIrequests+0x490	D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:1608
#	0x8446f4	github.com/nats-io/nats-server/v2/server.(*Server).mqttCreateAccountSessionManager.func2+0x74	D:/project/src/github.com/nats-io/nats-server/server/mqtt.go:995

1 @ 0x437a96 0x447832 0x8bbf05 0x467ba1
#	0x8bbf04	github.com/nats-io/nats-server/v2/server.(*sendq).internalLoop+0x1e4	D:/project/src/github.com/nats-io/nats-server/server/sendq.go:57

1 @ 0x437a96 0x447832 0x8cf8a7 0x467ba1
#	0x8cf8a6	github.com/nats-io/nats-server/v2/server.(*Server).handleSignals.func1+0xa6	D:/project/src/github.com/nats-io/nats-server/server/signal.go:47

1 @ 0x437a96 0x464b6e 0x918e15 0x467ba1
#	0x464b6d	time.Sleep+0x12d		c:/go/src/runtime/time.go:193
#	0x918e14	main.debug_print_goroutine+0xd4	D:/project/src/github.com/nats-io/nats-server/main.go:134

1 @ 0x437b6d 0x4057a9 0x4055cd 0x406725 0x89dc51 0x75ed50 0x7645ef 0x8b16b9 0x760556 0x88a08a 0x752cba 0x8b7ae5 0x467ba1
#	0x89dc50	github.com/nats-io/nats-server/v2/server.(*raft).handleAppendEntryResponse+0xf0		D:/project/src/github.com/nats-io/nats-server/server/raft.go:2748
#	0x75ed4f	github.com/nats-io/nats-server/v2/server.(*client).deliverMsg+0xbaf			D:/project/src/github.com/nats-io/nats-server/server/client.go:3147
#	0x7645ee	github.com/nats-io/nats-server/v2/server.(*client).processMsgResults+0x9ae		D:/project/src/github.com/nats-io/nats-server/server/client.go:4122
#	0x8b16b8	github.com/nats-io/nats-server/v2/server.(*client).processInboundRoutedMsg+0x158	D:/project/src/github.com/nats-io/nats-server/server/route.go:443
#	0x760555	github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg+0x35		D:/project/src/github.com/nats-io/nats-server/server/client.go:3460
#	0x88a089	github.com/nats-io/nats-server/v2/server.(*client).parse+0x21a9				D:/project/src/github.com/nats-io/nats-server/server/parser.go:477
#	0x752cb9	github.com/nats-io/nats-server/v2/server.(*client).readLoop+0xe39			D:/project/src/github.com/nats-io/nats-server/server/client.go:1174
#	0x8b7ae4	github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func1+0x24		D:/project/src/github.com/nats-io/nats-server/server/route.go:1375

1 @ 0x4620a5 0x6ae2f5 0x6ae10d 0x6ab28b 0x6b9e9a 0x6baa4e 0x653b0f 0x655409 0x65673b 0x652c48 0x467ba1
#	0x4620a4	runtime/pprof.runtime_goroutineProfileWithLabels+0x24	c:/go/src/runtime/mprof.go:746
#	0x6ae2f4	runtime/pprof.writeRuntimeProfile+0xb4			c:/go/src/runtime/pprof/pprof.go:724
#	0x6ae10c	runtime/pprof.writeGoroutine+0x4c			c:/go/src/runtime/pprof/pprof.go:684
#	0x6ab28a	runtime/pprof.(*Profile).WriteTo+0x14a			c:/go/src/runtime/pprof/pprof.go:331
#	0x6b9e99	net/http/pprof.handler.ServeHTTP+0x499			c:/go/src/net/http/pprof/pprof.go:253
#	0x6baa4d	net/http/pprof.Index+0x12d				c:/go/src/net/http/pprof/pprof.go:371
#	0x653b0e	net/http.HandlerFunc.ServeHTTP+0x2e			c:/go/src/net/http/server.go:2046
#	0x655408	net/http.(*ServeMux).ServeHTTP+0x148			c:/go/src/net/http/server.go:2424
#	0x65673a	net/http.serverHandler.ServeHTTP+0x43a			c:/go/src/net/http/server.go:2878
#	0x652c47	net/http.(*conn).serve+0xb07				c:/go/src/net/http/server.go:1929

1 @ 0x467ba1

**Comment by carr123** [comment]
@derekcollison hello, first congratulations for nats-server release v2.5.0.
i test mqtt againt nats-server 2.5.0 linux-amd64.  (i build my own binary)
i made 1000 mqtt client connections
1. notice there are 1001 subdirectories under $MQTT_msgs/obs/, i doubt if i made 100K connections, whether the folder count will exceed linux limits.
2. also notice there are too many(7046) goroutines, maybe they cost too much RAM space.
  the file writer and raft logic takes many goroutines. i'm not sure if these code could be optimized.
3. sometimes, clients connection fail ("Connecting to tcp://10.91.26.226:1883 CONNACK was not CONN_ACCEPTED, but rather Connection Error"), then subdirectory count under $MQTT_msgs/obs/ still increase, the goroutine count increase accordingly.
and these folder are never deleted even after server restart.

you mentioned "mux 1 stream for all MQTT clients on a server", the sessions are now  indeed merged into a single $MQTT_sess folder. i wonder whether the obs subfolders could be merged  then goroutines and memory usage are saved.

thanks.

below are logs from http/pprof:
https://github.com/carr123/natsjsmdemo/blob/main/goroutine.txt

**Comment by derekcollison** [comment]
@carr123, @kozlovic did most of the work here so will let him chime in regarding architecture.

Go routines are designed to be very lightweight, so not too overly concerned about using them for dedicated I/O. IIRC stack memory footprint is 8k per.

**Comment by carr123** [comment]
well，a connection cost N goroutines，that  design philosophy  is OK。what I saw is 4000 MQTT connections（no data sent yet）make one node cost 8GB RAM , that's too expensive i think。even after 4000 clients disconnected and node restarted，Nats still take that much memory。
another thing i saw is there maybe goroutine leak， when one node crash ，another node  create 50000 goroutines before it panic & exit

发自我的iPhone

**Comment by derekcollison** [comment]
Let's see what @kozlovic has to say next week.

**Comment by kozlovic** [comment]
@carr123 Are those connections creating each a subscription? That this the only reason I can think of that you see a file per connection under `$MQTT_msgs/obs`. If your connections are not created with the "clean session" flag, the server has to maintain the state when shutting down. So this is normal they persist.

The reason for so many go routines and memory usage is that for go routines we have 2 per connections (the read loop and write loop, regardless of MQTT client or standard NATS), then you have go routines for the RAFT related things for consumer leaders, etc.. 
Each consumer (that is one per your MQTT subscription) will have a raft group associated. Each group create many things, including these kind of objects:
```
		propc:    make(chan *Entry, 8192),
		entryc:   make(chan *appendEntry, 32768),
		respc:    make(chan *appendEntryResponse, 32768),
		applyc:   make(chan *CommittedEntry, 32768),
```
and maybe there are some buffers for each file store (where messages/consumers/etc..), which can explain the memory usage? 
When running in standalone mode, I don't see a "lot" of memory usage for 4,000 connections with 1 sub each. In clustered mode, much more, but creating those 4,000 connections is very slow. I am only at 2,200 as I type and each server is already at 2.5 GB.

I will defer to @derekcollison for that.

**Comment by carr123** [comment]
thanks for your detailed description about nats design. 
i created mqtt connections in a loop, each connection has fixed client_id, sub 1 topic, clean_session=false, and they connect evenly to a 3-node cluster.  that 's emulating real world scene.  when i said 1000 connections, means 1000 for each node.
i haven't test on standaone server yet. next week i will have a try.
i agree with you that there are might be buffers that occupy much memory, if it's optimized, then a single node can sustain more   
 connections. i expect  one node can hold 100K clients with light data traffic. that would be nice.
i you want to repoduce other issue i mentioned above, just continue making more connections till one node crash. then watch things happen on other nodes.

**Comment by MauriceVanVeen** [comment]
Closing since this issue already is quite old, that specific log line doesn't exist anymore, and handling has been greatly improved since.

For context: at this time our latest versions are 2.10.29 and 2.11.6. Specifically since 2.10.23 we've fixed quite some replication-related bugs as well.
