### ISSUE TITLE
nats-server  slice bounds out of range

### ISSUE THREAD

**Issue by izarraga** [nats-io/nats-server#2544]
[2129626] 2021/09/19 20:03:14.358456 [INF] Starting nats-server
[2129626] 2021/09/19 20:03:14.358544 [INF]   Version:  2.5.1-beta.3
[2129626] 2021/09/19 20:03:14.358551 [INF]   Git:      [not set]
[2129626] 2021/09/19 20:03:14.358556 [DBG]   Go build: go1.17.1
[2129626] 2021/09/19 20:03:14.358562 [INF]   Name:     nats-server-post
[2129626] 2021/09/19 20:03:14.358568 [INF]   Node:     qMvPUrcA
[2129626] 2021/09/19 20:03:14.358574 [INF]   ID:       NDI6JPZ3XDCWONBGNG3ZH6H73L346TGMIS775JTNERPGSJTW5D7MA4AM
[2129626] 2021/09/19 20:03:14.358584 [INF] Using configuration file: /usr/local/etc/nats-server-post.conf
[2129626] 2021/09/19 20:03:14.358640 [DBG] Created system account: "$SYS"
[2129626] 2021/09/19 20:03:14.359216 [INF] Starting JetStream
[2129626] 2021/09/19 20:03:14.359395 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
[2129626] 2021/09/19 20:03:14.359406 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[2129626] 2021/09/19 20:03:14.359411 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[2129626] 2021/09/19 20:03:14.359416 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[2129626] 2021/09/19 20:03:14.359421 [INF] 
[2129626] 2021/09/19 20:03:14.359426 [INF]          https://docs.nats.io/jetstream
[2129626] 2021/09/19 20:03:14.359430 [INF] 
[2129626] 2021/09/19 20:03:14.359438 [INF] ---------------- JETSTREAM ----------------
[2129626] 2021/09/19 20:03:14.359450 [INF]   Max Memory:      10.00 MB
[2129626] 2021/09/19 20:03:14.359456 [INF]   Max Storage:     900.00 MB
[2129626] 2021/09/19 20:03:14.359462 [INF]   Store Directory: "/var/nats/jetstream"
[2129626] 2021/09/19 20:03:14.359467 [INF] -------------------------------------------
[2129626] 2021/09/19 20:03:14.359552 [DBG]   Exports:
[2129626] 2021/09/19 20:03:14.359558 [DBG]      $JS.API.>
[2129626] 2021/09/19 20:03:14.359597 [DBG] Enabled JetStream for account "$G"
[2129626] 2021/09/19 20:03:14.359608 [DBG]   Max Memory:      -1 B
[2129626] 2021/09/19 20:03:14.359616 [DBG]   Max Storage:     -1 B
[2129626] 2021/09/19 20:03:14.359635 [DBG] Recovering JetStream state for account "$G"
[2129626] 2021/09/19 20:03:14.420453 [INF]   Restored 168 messages for stream "aikodb"
[2129626] 2021/09/19 20:03:14.420600 [INF]   Recovering 5 consumers for stream - "aikodb"
[2129626] 2021/09/19 20:03:14.523977 [INF]   Restored 7,920 messages for stream "aikopsender"
[2129626] 2021/09/19 20:03:14.524084 [INF]   Recovering 1 consumers for stream - "aikopsender"
[2129626] 2021/09/19 20:03:14.524312 [DBG] JetStream state for account "$G" recovered
[2129626] 2021/09/19 20:03:14.524782 [INF] Starting http monitor on 192.168.109.177:4223
[2129626] 2021/09/19 20:03:14.524879 [INF] Listening for client connections on 192.168.109.177:4222
[2129626] 2021/09/19 20:03:14.524896 [INF] Server is ready

Sep 19 20:02:13 pagasarri systemd[1]: Started nats-server-post.
Sep 19 20:03:10 pagasarri nats-server[2129551]: panic: runtime error: slice bounds out of range [2284012:0]
Sep 19 20:03:10 pagasarri nats-server[2129551]: goroutine 38 [running]:
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*msgBlock).cacheLookup(0xc000164b60, 0x224e7b)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/filestore.go:3179 +0x525
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*msgBlock).fetchMsg(0xc000164b60, 0x8)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/filestore.go:3104 +0x95
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*fileStore).msgForSeq(0xc000178280, 0x0)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/filestore.go:3239 +0x174
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*fileStore).LoadMsg(0xc000026cf0, 0xc0000a8384)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/filestore.go:3311 +0x19
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*consumer).getNextMsg(0xc000080380)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/consumer.go:2047 +0x413
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*consumer).processNextMsgReq.func2(0xc00005ea00)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/consumer.go:1913 +0xfd
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*consumer).processNextMsgReq(0xc000080380, 0xc0000e1140, 0xc000609300, 0x1d, {0x0, 0xc0000a8300}, {0xc0000d22a0, 0x1d}, {0xc0000a83d5, 0x20, ...})
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/consumer.go:1935 +0x712
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc000609300, 0xc00016d8c0, 0x21a176, {0xc0000a8384, 0x21d0f4, 0x7c}, {0xc0000a83b3, 0x220021, 0x4d}, {0xc00060a781, ...}, ...)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/client.go:3147 +0xbb0
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc000609300, 0xc000613938, 0xc000605c20, {0xc0000a83d5, 0x22, 0x2b}, {0x0, 0x0, 0xc000072120}, {0xc0000a8384, ...}, ...)
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/client.go:4122 +0x9af
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0xc000609300, {0xc0000a83d5, 0x2, 0x2b})
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/client.go:3611 +0xa71
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg(0xc000609300, {0xc0000a83d5, 0x4f, 0x6091fc3e3c019})
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/client.go:3458 +0x3d
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).parse(0xc000609300, {0xc0000a8380, 0x77, 0x95e200})
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/parser.go:477 +0x21aa
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc000609300, {0x0, 0x0, 0x0})
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/client.go:1174 +0xe3a
Sep 19 20:03:10 pagasarri nats-server[2129551]: github.com/nats-io/nats-server/v2/server.(*Server).createClient.func1()
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/server.go:2448 +0x29
Sep 19 20:03:10 pagasarri nats-server[2129551]: created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
Sep 19 20:03:10 pagasarri nats-server[2129551]:         /usr/src/nats-server/server/server.go:2867 +0x87
Sep 19 20:03:10 pagasarri systemd[1]: nats-server-post.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 20:03:10 pagasarri systemd[1]: nats-server-post.service: Failed with result 'exit-code'.

**Comment by derekcollison** [comment]
Working on a branch and PR to fix. Should land soon.

Feel free to take a look here and run against this branch if you can.

https://github.com/nats-io/nats-server/tree/fs-stable
