### ISSUE TITLE
Panic in jsz monitoring endpoint

### ISSUE THREAD

**Issue by rh2048** [nats-io/nats-server#2741]
## Defect

Setting up prometheus-nats-exporter as a sidecar to a JetStream-enabled NATS server causes the server to panic when enabling the `jsz` endpoint.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output (unable to reproduce in a staging environment)
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

Server: Docker `nats:2.6.6`

#### OS/Container environment:

Ubuntu 20.04

#### Steps or code to reproduce the issue:

1. Setup a 3-node JetStream-enabled cluster
2. Run `natsio/prometheus-nats-exporter:0.9.0` as a sidecar with the following flags:
  ```
  - "-varz"
  - "-connz"
  - "-gatewayz"
  - "-leafz"
  - "-routez"
  - "-subz"
  - "-jsz"
  - "all"
  - "-use_internal_server_id"
  ```
3. Let the server run for a while with significant throughput. Cannot reproduce consistently.

#### Expected result:

Server should not panic.

#### Actual result:

Server panics with the following stack trace:

```
[1] 2021/12/13 02:43:57.932070 [ERR] monitoring: panic serving XXXX: runtime error: invalid memory address or nil pointer dereference
goroutine 2121586 [running]:
net/http.(*conn).serve.func1(0xc00016a320)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:1804 +0x153
panic(0xa547a0, 0xece5d0)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/runtime/panic.go:971 +0x499
github.com/nats-io/nats-server/server.(*Server).accountDetail(0xc00018c000, 0xc0000f8000, 0x101, 0xc0042b8ea0)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2478 +0x68a
github.com/nats-io/nats-server/server.(*Server).Jsz(0xc00018c000, 0xc002177a80, 0xb0409a, 0x3, 0xf0de60)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2627 +0x7e6
github.com/nats-io/nats-server/server.(*Server).HandleJsz(0xc00018c000, 0xbd2b40, 0xc0023601c0, 0xc000140000)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/monitor.go:2667 +0x3d8
net/http.HandlerFunc.ServeHTTP(0xc00017a9f0, 0xbd2b40, 0xc0023601c0, 0xc000140000)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:2049 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00017c3c0, 0xbd2b40, 0xc0023601c0, 0xc000140000)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:2428 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0001f2000, 0xbd2b40, 0xc0023601c0, 0xc000140000)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc00016a320, 0xbd4b68, 0xc000928880)
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.16.10.linux.amd64/src/net/http/server.go:2993 +0x39b
```

**Comment by ripienaar** [comment]
https://github.com/nats-io/nats-server/pull/2743 should fix it, but @derekcollison might have a better fix or idea
