### ISSUE TITLE
Strange behaviour using KeyValue store

### ISSUE THREAD

**Issue by apuckey** [nats-io/nats-server#3626]
Hi,

I realise there wont be much information here initially, however I'll put what I have until I can get a reproducible test case.

nats-server -DV
```
# nats-server -DV
[21] 2022/11/14 23:21:59.234003 [INF] Starting nats-server
[21] 2022/11/14 23:21:59.234045 [INF]   Version:  2.9.6
[21] 2022/11/14 23:21:59.234048 [INF]   Git:      [289a9e1]
[21] 2022/11/14 23:21:59.234054 [DBG]   Go build: go1.19.3
```

I have a 5 server cluster running via docker, server configs are as follows:
```
port: 4222
http_port: 8222
server_name: nats-x
client_advertise: 10.x.xx.20
cluster {
  name: "dnCluster"
  port: 6222
  cluster_advertise: 10.x.xx.20:6222
  routes = [
    nats-route://10.x.xx.20:6222
    nats-route://10.x.xx.20:6222
    nats-route://10.x.xx.20:6222
    nats-route://10.x.xx.20:6222
  ]
}
accounts {
 $SYS { users = [ { user: "admin", pass: "xxxx" } ] }
}
jetstream {
  store_dir: /data
  max_memory_store: 268435456
}
```

Creating the KeyValue stores using the go client then php clients can use it via grpc:
TTL is various but generally is around 4 hours
```
s.JetStream.CreateKeyValue(&nats.KeyValueConfig{
		Bucket:      bucket,
		Description: "Session Storage",
		History:     1,
		TTL:         time.Duration(ttl),
		Storage:     nats.FileStorage,
		Replicas:    3,
	})
```

The nats server is generally doing around 5000msg/sec however this issue seems to happen at any time.

Issue 1: 
Random server starts displaying this in the logs even though all servers are up, once this happens these keyvalue stores are non-functioning. Deleting them via cli has no effect ( if it even lets you delete them ). If you manage to delete them you can no longer create a new KeyValue store with the same name.

```
[1] 2022/11/14 06:23:24.196626 [WRN] JetStream cluster stream '$G > KV_SESSION_e0b58a5b-c238-45d3-8ada-837d9bfdeea9' has NO quorum, stalled
[1] 2022/11/14 06:23:27.610976 [WRN] JetStream cluster stream '$G > KV_SESSION_e64684f5-591a-44f3-9478-ed73cfcb233f' has NO quorum, stalled
[1] 2022/11/14 06:23:28.135742 [WRN] JetStream cluster stream '$G > KV_SESSION_02e19464-2a6c-465c-b250-36de31fd643e' has NO quorum, stalled
```

Issue 2:
random segfault:
```
[1] 2022/11/14 09:16:43.271775 [INF] Self is new JetStream cluster metadata leader

2022-11-14T09:41:45.350514792Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x3b2ca8]
 
goroutine 20 [running]:
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamInfoRequest(0x0?, 0x0?, 0x40000b0000, 0x0?, {0x40012713b0, 0x43}, {0x40027c6c90, 0x11}, {0x4002524400, 0x7e, ...})
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_api.go:1786 +0x958
github.com/nats-io/nats-server/v2/server.(*jetStream).apiDispatch(0x40000f8000, 0x40000de480, 0x40000b0000, 0x4000112d80, {0x40012713b0, 0x43}, {0x40027c6c90, 0x11}, {0x4002524400, 0x7e, ...})
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_api.go:764 +0x1cc
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0x40000b0000, 0x0, 0x40000de480, 0x40027c6c78?, {0x4001271180, 0x43, 0x50}, {0x40027c6c78, 0x11, 0x18}, ...)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:3194 +0xa54
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0x40000b0000, 0x4000112d80, 0x40015ae810, {0x4002524400, 0x80, 0x80}, {0x0, 0x0, 0x5d7200?}, {0x4001271180, ...}, ...)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:4235 +0x74c
github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0x40000b0000, {0x4002524400, 0x80, 0x80})
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/client.go:3660 +0x9d4
github.com/nats-io/nats-server/v2/server.(*Server).internalSendLoop(0x400019e000, 0x0?)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/events.go:428 +0xd60
created by github.com/nats-io/nats-server/v2/server.(*Server).setSystemAccount
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:1278 +0x308

[1] 2022/11/14 09:17:14.865616 [INF] 10.x.xx.20:6222(nats-e) - rid:6 - Router connection closed: Read Error

node-e:

[1] 2022/11/14 09:16:43.272941 [INF] JetStream cluster new metadata leader: nats-b/dnCluster

2022-11-14T09:17:14.863325825Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x3b2ca8]
goroutine 13 [running]:
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamInfoRequest(0x0?, 0x0?, 0x4000197980, 0x400018e6f0?, {0x4000818aa0, 0x43}, {0x4000b922b8, 0x11}, {0x4000b4ad80, 0x7e, ...})
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_api.go:1786 +0x958
github.com/nats-io/nats-server/v2/server.(*Server).processJSAPIRoutedRequests(0x400011e000)
/home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_api.go:796 +0x27c
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
/home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:3077 +0xbc
```

The issue still happens if I stop all nodes, remove data and restart them all ( as if booting a new cluster )

These 2 things may be related and unfortunately I don't have the docker logs from the previous time it happened to check for segfaults.

In the mean time I'm trying to create a reproducible environment locally.

**Comment by apuckey** [comment]
@kozlovic thanks for the quick fix, do you think this could of caused the other issues?

**Comment by kozlovic** [comment]
@apuckey No, I would think the other way around. The NO quorum change likely is actually the root of the panic in that the stream info happened at the wrong time, which is fixed by the PR. So I am re-opening this issue (that was closed automatically because I referenced it in the PR that was merged).

**Comment by apuckey** [comment]
Could the other part of this be related to [3677 ](https://github.com/nats-io/nats-server/issues/3677).

I do see a lot of similar messages in my client which i assumed was related to something else:
```
[ERROR Nov 14 10:21:36.857161939, service.go:254] [SetSession|3cdd4f93-573d-4632-9a18-7fe73aec2ace]: unable to put data into keyvalue store: nats: no response from stream
[ERROR Nov 14 10:21:47.000352251, service.go:254] [SetSession|3cdd4f93-573d-4632-9a18-7fe73aec2ace]: unable to put data into keyvalue store: nats: no response from stream
[ERROR Nov 14 10:21:51.572191536, service.go:254] [SetSession|3cdd4f93-573d-4632-9a18-7fe73aec2ace]: unable to put data into keyvalue store: nats: no response from stream
[ERROR Nov 14 10:22:14.497582744, service.go:524] [getKeyValue]: Unable to create/get key value store from jetstram: context deadline exceeded
[ERROR Nov 14 10:22:14.497610650, service.go:150] [GetSession|81371b30-191c-4381-92dc-f416db4c92e2]: unable to get key/value store from jetstream: nats-bridge: An unknown error has occured
[ERROR Nov 14 10:22:19.498045006, service.go:524] [getKeyValue]: Unable to create/get key value store from jetstram: context deadline exceeded
[ERROR Nov 14 10:22:24.500563254, service.go:524] [getKeyValue]: Unable to create/get key value store from jetstram: context deadline exceeded
[ERROR Nov 14 10:22:24.500760544, service.go:150] [GetSession|81371b30-191c-4381-92dc-f416db4c92e2]: unable to get key/value store from jetstream: nats-bridge: An unknown error has occured
[ERROR Nov 14 10:23:31.092932690, service.go:524] [getKeyValue]: Unable to create/get key value store from jetstram: context deadline exceeded
[ERROR Nov 14 10:23:31.092966003, service.go:150] [GetSession|c8e51d1d-fbde-437c-8d8c-1f081813740a]: unable to get key/value store from jetstream: nats-bridge: An unknown error has occured
```

**Comment by derekcollison** [comment]
Any more updates with this?

**Comment by apuckey** [comment]
@derekcollison I'm having issues replicating it in a local environment, need a bit more time to come up with a repro

**Comment by derekcollison** [comment]
What server version are you testing?

**Comment by derekcollison** [comment]
ok keep us posted.

**Comment by derekcollison** [comment]
Will close the issue but feel free to reopen if needed.
