### ISSUE TITLE
Expect lastSubjectSequence giving same result as lastSequence

### ISSUE THREAD

**Issue by Vinceveve** [nats-io/nats-server#3716]
## Defect
When publishing on a given subject with an expected last subject sequence.
The messages from the other subjects on the stream are counted as part of the sequence.

Tried it with expect param and by setting headers manually,  with same results.
Digging in I think it's a NATS server issue.
The node library is straightforward and just pass the header to the server

#### Versions of `nats-server` and affected client libraries used:
```
[1] 2022/12/15 14:50:00.766733 [INF] Starting nats-server
[1] 2022/12/15 14:50:00.766806 [INF]   Version:  2.9.9
[1] 2022/12/15 14:50:00.766809 [INF]   Git:      [825949b]
[1] 2022/12/15 14:50:00.766810 [DBG]   Go build: go1.19.4
[1] 2022/12/15 14:50:00.766811 [INF]   Name:     NBWRXIWLZMWYB2LHDAP562Y7GZJ64K7EO7XXP7SNWYUFQIG6JV2D7QC6
[1] 2022/12/15 14:50:00.766813 [INF]   ID:       NBWRXIWLZMWYB2LHDAP562Y7GZJ64K7EO7XXP7SNWYUFQIG6JV2D7QC6
[1] 2022/12/15 14:50:00.766842 [DBG] Created system account: "$SYS"
[1] 2022/12/15 14:50:00.767265 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2022/12/15 14:50:00.767280 [DBG] Get non local IPs for "0.0.0.0"
[1] 2022/12/15 14:50:00.767408 [DBG]   ip=172.17.0.3
[1] 2022/12/15 14:50:00.767426 [INF] Server is ready
[1] 2022/12/15 14:50:00.767695 [DBG] maxprocs: Leaving GOMAXPROCS=5: CPU quota undefined
```

Library used : Node latest version 
```
"nats": "2.9.2",
```

#### OS/Container environment: 
Official docker image on OSX(ARM) and official docker image on ubuntu (x86)

#### Steps or code to reproduce the issue:
```typescript
import { connect, Empty, headers } from "nats";

const main = async () => {
  const nc = await connect({
    servers: "127.0.0.1:4222",
  });
  const jsm = await nc.jetstreamManager();
  const js = nc.jetstream();

  const stream = "mystream";
  console.log(`Create stream ${stream}`);
  await jsm.streams.add({ name: stream, subjects: [`${stream}.*`] });

  console.log(`Publish on ${stream}.a`);
  await js.publish(`${stream}.a`, Empty);

  console.log(`Publish on ${stream}.b`);
  await js.publish(`${stream}.b`, Empty);

  console.log(
    `Publish on ${stream}.a expecting its in 2nd position on the subject`
  );
  await js.publish(`${stream}.a`, Empty, {
    expect: { lastSubjectSequence: 1 },
  });
  // It should be ok but : NatsError: wrong last sequence: 3
 
  await js.publish(`${stream}.a`, Empty, {
    expect: { lastSubjectSequence: 2 },
  });
//   const h = headers();
//  h.set("Nats-Expected-Last-Subject-Sequence", "2");
// await js.publish(`${stream}.a`, Empty, { headers: h });

  await jsm.streams.delete(stream);
  process.exit();
};
main();
```
#### Expected result:
OK 

#### Actual result:
```
NatsError: wrong last sequence: 3
    at checkJsErrorCode (/Users/vincentvermersch/Sites/eventmodeling/common/temp/node_modules/.pnpm/nats@2.9.2/node_modules/nats/nats-base-client/jsutil.ts:213:14)
    at JetStreamClientImpl.parseJsResponse (/Users/vincentvermersch/Sites/eventmodeling/common/temp/node_modules/.pnpm/nats@2.9.2/node_modules/nats/nats-base-client/jsbaseclient_api.ts:106:35)
    at JetStreamClientImpl.<anonymous> (/Users/vincentvermersch/Sites/eventmodeling/common/temp/node_modules/.pnpm/nats@2.9.2/node_modules/nats/nats-base-client/jsclient.ts:198:21)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vincentvermersch/Sites/eventmodeling/common/temp/node_modules/.pnpm/nats@2.9.2/node_modules/nats/lib/nats-base-client/jsclient.js:19:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: '400',
  chainedError: undefined,
  api_error: { code: 400, err_code: 10071, description: 'wrong last sequence: 3' }
}
```

```
> nats stream view mystream
[1] Subject: mystream.a Received: 2022-12-15T15:46:55+01:00

nil body
[2] Subject: mystream.b Received: 2022-12-15T15:46:55+01:00

nil body
[3] Subject: mystream.a Received: 2022-12-15T15:46:55+01:00

  Nats-Expected-Last-Subject-Sequence: 1

nil body
16:01:25 Reached apparent end of data
```

meaning it counts mystream.b subject on the sequence

**Comment by derekcollison** [comment]
Sequence numbers on a stream are monotonic for every message stored. So 3 is the correct sequence to be expected in that case, not 1.

Not that header is mostly used with sequence 0, meaning make sure this is the first msg on this subject.

**Comment by Vinceveve** [comment]
For a stream I totally agree `lastSequence`.

But for the subject ? here I have only 2 messages on my subject so 2 should be the correct subject sequence.
If I know before the order of my events how can I calculate the sequence before ? (with 100 subjects in the same stream)

The lastSubjectSequence: 0 is buggy too, if the subject exists or not it writes it down. 

lastSequence is working just fine for both.

ps. thank you for the answer, I'm a huge fan of your work !

**Comment by derekcollison** [comment]
There is not such thing as a subject sequence. That header allows you to match both subject and sequence, but again it would be 3 in your example.

If lastSubjectSequence:0 sees a message there already for the given subject it will fail. Are you saying you think this is not the case?

**Comment by Vinceveve** [comment]
Nats-Expected-Last-Sequence does the check regardless of the subject. Nats-Expected-Last-Subject-Sequence does the check for the subject. 
The sequence number is incremented overall, not per subject.

foo -> 1, bar -> 2, foo -> 3

rather than foo -> 1, bar -> 1 (independent sequence numbers per subject within a stream)

Closing, Thank you !
