### ISSUE TITLE
pull consumer with expires, will not notify when consumer is deleted

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#3969]
Here's a test you can run - the pull consumer will correctly get notified when the consumer is deleted, but the pull request will simply timeout

https://github.com/nats-io/nats.deno/pull/495/files

`deno test -A --filter "jetstream - consumer deleted"`

```
< PUB $JS.API.CONSUMER.DELETE.IBWGDUUAOLKZAJ5Y4T087L.IBWGDUUAOLKZAJ5Y4T087L _INBOX.IBWGDUUAOLKZAJ5Y4T08G1.IBWGDUUAOLKZAJ5Y4T09DT 0␍␊␍␊
> HMSG _INBOX.IBWGDUUAOLKZAJ5Y4T08SP 2  33 33␍␊NATS/1.0 409 Consumer Deleted␍␊␍␊␍␊MSG _INBOX.IBWGDUUAOLKZAJ5Y4T08G1.IBWGDUUAOLKZAJ5Y4T09DT 1 75␍␊{"type":"io.nats.jetstream.api.v1.consumer_delete_response","success":true}␍␊
pull NatsError: consumer deleted
    at checkJsErrorCode (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsutil.ts:218:14)
    at checkJsError (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsutil.ts:157:10)
    at JetStreamClientImpl.pull (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsclient.ts:227:17)
< UNSUB 2␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.IBWGDUUAOLKZAJ5Y4T087L.x _INBOX.IBWGDUUAOLKZAJ5Y4T095D 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
> PING␍␊
< PONG␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.IBWGDUUAOLKZAJ5Y4T087L.x _INBOX.IBWGDUUAOLKZAJ5Y4T095D 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.IBWGDUUAOLKZAJ5Y4T087L.x _INBOX.IBWGDUUAOLKZAJ5Y4T095D 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
> HMSG _INBOX.IBWGDUUAOLKZAJ5Y4T095D 3  81 81␍␊NATS/1.0 408 Request Timeout␍␊Nats-Pending-Messages: 1␍␊Nats-Pending-Bytes: 0␍␊␍␊␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.IBWGDUUAOLKZAJ5Y4T087L.x _INBOX.IBWGDUUAOLKZAJ5Y4T095D 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
> HMSG _INBOX.IBWGDUUAOLKZAJ5Y4T095D 3  81 81␍␊NATS/1.0 408 Request Timeout␍␊Nats-Pending-Messages: 1␍␊Nats-Pending-Bytes: 0␍␊␍␊␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.IBWGDUUAOLKZAJ5Y4T087L.x _INBOX.IBWGDUUAOLKZAJ5Y4T095D 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
> HMSG _INBOX.IBWGDUUAOLKZAJ5Y4T095D 3  81 81␍␊NATS/1.0 408 Request Timeout␍␊Nats-Pending-Messages: 1␍␊Nats-Pending-Bytes: 0␍␊␍␊␍
```

**Comment by derekcollison** [comment]
Which server version?

**Comment by derekcollison** [comment]
This is by design. We short circuit this and direct gets from the service import chain since they are handled directly.

We could look into figuring out if there are no responders, but then we would pay the costs of the service imports and these are expected to be on the hot path.

But will take a look.

**Comment by scottf** [comment]
If heartbeats are on for the pull, clients should notice that heartbeats were missed and raise that, so it might not matter that we don't see anything, it just won't be instantaneous. For simplification we will always have hb's on.

**Comment by derekcollison** [comment]
I get nervous with this direction, simply due to the fact that we could have 100s of thousands of these in some systems, or more.

**Comment by aricart** [comment]
@Jarema apologies that test is incorrect, the server is doing the right thing.

**Comment by aricart** [comment]
```
< SUB _INBOX.YBTZ17YI3WL1LRDP1REEH7 2␍␊UNSUB 2 1␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.one _INBOX.YBTZ17YI3WL1LRDP1REEH7 50␍␊{"batch":1,"no_wait":false,"expires":150000000000}␍␊
< PUB $JS.API.CONSUMER.INFO.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REEO7 0␍␊␍␊
> MSG _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REEO7 1 530␍␊{"type":"io.nats.jetstream.api.v1.consumer_info_response","stream_name":"YBTZ17YI3WL1LRDP1REDB7","name":"two","created":"2023-03-16T14:42:13.168869Z","config":{"durable_name":"two","name":"two","deliver_policy":"all","ack_policy":"explicit","ack_wait":30000000000,"max_deliver":-1,"replay_policy":"instant","max_waiting":512,"max_ack_pending":1000,"num_replicas":0},"delivered":{"consumer_seq":0,"stream_seq":0},"ack_floor":{"consumer_seq":0,"stream_seq":0},"num_ack_pending":0,"num_redelivered":0,"num_waiting":0,"num_pending":0}␍␊
< SUB _INBOX.YBTZ17YI3WL1LRDP1REEV7 3␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
> PING␍␊
< PONG␍␊
< PUB $JS.API.CONSUMER.DELETE.YBTZ17YI3WL1LRDP1REDB7.one _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REF27 0␍␊␍␊
< PUB $JS.API.CONSUMER.DELETE.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REF97 0␍␊␍␊


> HMSG _INBOX.YBTZ17YI3WL1LRDP1REEH7 2  33 33␍␊NATS/1.0 409 Consumer Deleted␍␊␍␊␍␊
one NatsError: consumer deleted
    at checkJsErrorCode (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsutil.ts:218:14)
    at checkJsError (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsutil.ts:157:10)
    at JetStreamClientImpl.pull (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/nats-base-client/jsclient.ts:227:17)
> HMSG _INBOX.YBTZ17YI3WL1LRDP1REEV7 3  33 33␍␊NATS/1.0 409 Consumer Deleted␍␊␍␊␍␊MSG _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REF27 1 75␍␊{"type":"io.nats.jetstream.api.v1.consumer_delete_response","success":true}␍␊MSG _INBOX.YBTZ17YI3WL1LRDP1REDP7.YBTZ17YI3WL1LRDP1REF97 1 75␍␊{"type":"io.nats.jetstream.api.v1.consumer_delete_response","success":true}␍␊
< UNSUB 2␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.YBTZ17YI3WL1LRDP1REDB7.two _INBOX.YBTZ17YI3WL1LRDP1REEV7 48␍␊{"batch":1,"no_wait":false,"expires":5000000000}␍␊
two done
```
