### ISSUE TITLE
panic: JetStream Cluster Unknown group entry op type: 8

### ISSUE THREAD

**Issue by Lemorz56** [nats-io/nats-server#4294]
We're running a JetStream cluster of 3 servers in Kubernetes. 

One of the servers exited with an error:
```
[1] [INF] JetStream cluster new consumer leader for '$G > archive > Kq7141Gp'
[1] [WRN] Error applying entries to '$G > archive': last sequence mismatch
panic: JetStream Cluster Unknown group entry op type: 8

goroutine 224 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyStreamEntries(0xc0001d6000, 0xc00022b880, 0x0?, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2841 +0x1ea7
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream(0xc0001d6000, 0xc00022b880, 0xc0000ce900, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2261 +0x290b
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:3538 +0x2a
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
    github.com/nats-io/nats-server/v2/server/server.go:3161 +0x85

```
I can't seem to find the trigger that caused the error. The stream that is mentioned is a mirror of a stream that is replicated on the 3 servers. The mirror is replicated as well.

After the restart all 3 servers are now using a lot of CPU. 
Not sure if the configuration is an issue or of this is an actual bug. The high CPU load is worrying me a bit as it does not seem to go down. Its been at its max now for 9h.

**Comment by derekcollison** [comment]
Which server version are you currently running?

**Comment by Lemorz56** [comment]
> Which server version are you currently running?
Oh sorry for not writing that, v2.9.19.

**Comment by Lemorz56** [comment]
I can also update that the CPU load happened precisely after the restart of one server and continued for about 10h. Not sure why.

**Comment by derekcollison** [comment]
Were you running the server with the profile port on? Were you able to capture any pprofs?

**Comment by Lemorz56** [comment]
No, sadly not 😞

**Comment by Lemorz56** [comment]
Received similar errors this night but this time there was no high CPU or Memory load afterwards.

nats-0 (this one had 2 restarts, but these are the logs before the last crash):
```
[1] 2023/07/11 16:39:14.414316 [INF]   Starting restore for stream '$G > archive'
[1] 2023/07/11 16:39:26.637938 [INF]   Restored 610,728 messages for stream '$G > archive'
[1] 2023/07/11 16:39:26.667377 [INF]   Starting restore for stream '$G > event-log'
[1] 2023/07/11 16:40:22.357631 [INF]   Restored 82,636,032 messages for stream '$G > event-log'
[1] 2023/07/11 16:40:22.357715 [INF]   Recovering 2 consumers for stream - '$G > archive'
[1] 2023/07/11 16:40:22.359065 [INF]   Recovering 3 consumers for stream - '$G > event-log'
[1] 2023/07/11 16:40:22.360592 [INF] Starting JetStream cluster
[1] 2023/07/11 16:40:22.360600 [INF] Creating JetStream metadata controller
[1] 2023/07/11 16:40:22.361677 [INF] JetStream cluster recovering state
[1] 2023/07/11 16:40:22.362547 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2023/07/11 16:40:22.362661 [INF] Server is ready
[1] 2023/07/11 16:40:22.362692 [INF] Cluster name is JETSTREAM
[1] 2023/07/11 16:40:22.362734 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2023/07/11 16:40:22.364976 [INF] xx.yy.zz.xy:6222 - rid:40 - Route connection created
[1] 2023/07/11 16:40:22.366719 [INF] xx.yy.zz.xy:50228 - rid:41 - Route connection created
[1] 2023/07/11 16:40:22.463294 [WRN] Waiting for routing to be established...
[1] 2023/07/11 16:40:24.120024 [INF] JetStream cluster new metadata leader: nats-2/JETSTREAM
[1] 2023/07/11 19:17:23.487360 [WRN] JetStream cluster stream '$G > archive' has NO quorum, stalled
[1] 2023/07/11 19:17:23.846000 [WRN] JetStream cluster stream '$G > event-log' has NO quorum, stalled
[1] 2023/07/11 19:17:29.345680 [INF] Self is new JetStream cluster metadata leader
[1] 2023/07/11 19:17:30.650894 [INF] JetStream cluster new stream leader for '$G > archive'
panic: JetStream Cluster Unknown group entry op type: 7

2023/07/11 19:57:11 goroutine 273 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyStreamEntries(0xc000316000, 0xc00015f500, 0x0?, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2841 +0x1ea7
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream(0xc000316000, 0xc00015f500, 0xc00015b0e0, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2261 +0x290b
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:3538 +0x2a
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
    github.com/nats-io/nats-server/v2/server/server.go:3161 +0x85

```

nats-1 has some "Router Connection Closed: Read Error" but other then that no issues.
Same time as nats-2 had the panic, it logged:
```
[1] 2023/07/11 21:50:14.669481 [INF] Self is new JetStream cluster metadata leader
```
which is understandable.

nats-2 (1 restart)
```
[1] 2023/07/11 12:39:22.159714 [WRN] Error applying entries to '$G > archive': last sequence mismatch
[1] 2023/07/11 12:39:22.228589 [WRN] Resetting stream cluster state for '$G > archive'
[1] 2023/07/11 13:02:20.758724 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 1974 != applied 1972
[1] 2023/07/11 13:02:20.758767 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:04:20.498780 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 1981 != applied 1978
[1] 2023/07/11 13:04:20.498818 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:06:20.499676 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 1989 != applied 1985
[1] 2023/07/11 13:06:20.499716 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:08:20.499502 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 1999 != applied 1995
[1] 2023/07/11 13:08:20.499539 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:10:20.499577 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2018 != applied 2011
[1] 2023/07/11 13:10:20.499615 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:12:20.498869 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2023 != applied 2020
[1] 2023/07/11 13:12:20.498908 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 13:14:20.499264 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2030 != applied 2026
[1] 2023/07/11 13:14:20.499297 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 14:56:20.499616 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2388 != applied 2383
[1] 2023/07/11 14:56:20.499657 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 14:58:20.499121 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2392 != applied 2390
[1] 2023/07/11 14:58:20.499159 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 15:00:20.499778 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2397 != applied 2395
[1] 2023/07/11 15:00:20.499813 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 16:39:13.191718 [INF] xx.yy.zz.xyz:37980 - rid:41 - Router connection closed: Client Closed
[1] 2023/07/11 16:39:14.266345 [INF] xx.yy.zz.xyz:37830 - rid:190 - Route connection created
[1] 2023/07/11 16:39:17.260599 [INF] Self is new JetStream cluster metadata leader
[1] 2023/07/11 16:39:20.452320 [INF] JetStream cluster new stream leader for '$G > event-log'
[1] 2023/07/11 17:04:55.386262 [WRN] Internal subscription on "$JS.API.CONSUMER.CREATE.event-log.mirror-8cVLfvsm.entity.*.1.>" took too long: 2.145820469s
[1] 2023/07/11 18:44:20.499754 [WRN] RAFT [BQKE9plJ - S-R3F-mfRNuj3x] Falling behind in health check, commit 2610 != applied 2608
[1] 2023/07/11 18:44:20.499791 [WRN] JetStream stream '$G > archive' is not current
[1] 2023/07/11 19:17:24.567597 [INF] JetStream cluster no metadata leader
[1] 2023/07/11 19:17:28.952669 [INF] JetStream cluster new stream leader for '$G > event-log'
[1] 2023/07/11 19:17:29.344115 [INF] JetStream cluster new metadata leader: nats-0/JETSTREAM
[1] 2023/07/11 19:57:11.623497 [INF] xx.yy.zz.xyz:49424 - rid:210 - Router connection closed: Client Closed
[1] 2023/07/11 19:57:15.703164 [INF] JetStream cluster new stream leader for '$G > archive'
[1] 2023/07/11 19:57:17.339245 [INF] Self is new JetStream cluster metadata leader
[1] 2023/07/11 19:58:21.144919 [INF] Catchup for stream '$G > event-log' complete
[1] 2023/07/11 19:59:17.437445 [INF] Catchup for stream '$G > archive' complete
[1] 2023/07/11 20:44:31.365785 [WRN] Error applying entries to '$G > archive': last sequence mismatch
[1] 2023/07/11 20:44:54.172566 [WRN] RAFT [BQKE9plJ - C-R3F-GGNjCCaL] Resetting WAL state
panic: JetStream Cluster Unknown group entry op type: 7

2023/07/11 21:50:09 goroutine 1599 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyStreamEntries(0xc0002b0000, 0xc004d16700, 0x1?, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2841 +0x1ea7
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorStream(0xc0002b0000, 0xc004d16700, 0xc01f1b0e10, 0x0)
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:2261 +0x290b
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateStream.func1()
    github.com/nats-io/nats-server/v2/server/jetstream_cluster.go:3538 +0x2a
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
    github.com/nats-io/nats-server/v2/server/server.go:3161 +0x85
```

I understand that this might not give much, but do you have any tips on troubleshooting? I was thinking of setting the replicas for the streams down to 1, and then try to set them to 3 again.

**Comment by derekcollison** [comment]
If the system is exhibiting the conditions, we could snapshot and tarball all the storage directories for each server with config and send it to us privately to take a look.

**Comment by wallyqs** [comment]
Closing for now since seems related to v2.9 series.
