### ISSUE TITLE
NATS server panic on [server.(*Account).selectMappedSubject] method call

### ISSUE THREAD

**Issue by igorrius** [nats-io/nats-server#4893]
### Observed behavior

With a high push rate, servers sometimes fail with a panic. This appears in the push rate of approximately 40-60K per second.

The short account configuration description follows:
```
...
accounts: {
    SERVICE: {
        users: [
            {user: "user1", password: "password1"}
        ]
        # subjects mapping
        mappings = {
            "requests.*": [
                {destination: "requests.$1.experimental", weight: 1%}
            ]
        }
    }
}
...
```
Subscribers for `requests.$1.experimental` can/can not present

Panic raw:

```
 panic: runtime error: index out of range [-2]

goroutine 7340 [running]:
math/rand.(*rngSource).Uint64(...)
	math/rand/rng.go:249
math/rand.(*rngSource).Int63(0x0?)
	math/rand/rng.go:234 +0x85
math/rand.(*Rand).Int63(...)
	math/rand/rand.go:96
math/rand.(*Rand).Int31(...)
	math/rand/rand.go:110
math/rand.(*Rand).Int31n(0xc00021e5a0, 0x64)
	math/rand/rand.go:145 +0x53
github.com/nats-io/nats-server/v2/server.(*Account).selectMappedSubject(0xc0001fd900, {0xc000616540, 0x15})
	github.com/nats-io/nats-server/v2/server/accounts.go:812 +0x327
github.com/nats-io/nats-server/v2/server.(*client).selectMappedSubject(0xc0003f0c80)
	github.com/nats-io/nats-server/v2/server/client.go:3748 +0x45
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc0003f0c80, {0xc0005d5680, 0x80, 0x80})
	github.com/nats-io/nats-server/v2/server/parser.go:488 +0x1ec6
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc0003f0c80, {0x0, 0x0, 0x0})
	github.com/nats-io/nats-server/v2/server/client.go:1371 +0x12fa
github.com/nats-io/nats-server/v2/server.(*Server).createClientEx.func1()
	github.com/nats-io/nats-server/v2/server/server.go:3217 +0x25
github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
	github.com/nats-io/nats-server/v2/server/server.go:3700 +0x32

```

### Expected behavior

The NATS server is working properly :) without panics.

The approximately **1%** mapped to `requests.$1.experimental`

### Server and client version

Server version: **v2.10.5**
Client version: **github.com/nats-io/nats.go v1.31.0**

### Host environment

GCP K8S runtime with NATS Helm chart https://github.com/nats-io/k8s modified only to add requested resources.

### Steps to reproduce

1. Create a cluster with 5 nodes.
2. Create subject mapping configuration.
3. Create subject push through up to 60K requests per second.
4. Wait for panic...

**Comment by igorrius** [comment]
Thanks!
