### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by rajpol** [nats-io/nats-server#4899]
### Observed behavior

One of the nats replica nats-2 is crash looped and never recovered due to this few streams and not available and getting timeouts

Nats version: v2.10.4
K8 version : v1.21.14

Error:
```
panic: runtime error: makeslice: cap out of range

goroutine 179 [running]:
github.com/nats-io/nats-server/v2/server.(*msgBlock).indexCacheBuf(0xc0002e01a0, {0x10800a0, 0x0, 0x0})
        github.com/nats-io/nats-server/v2/server/filestore.go:4917 +0x1aa
github.com/nats-io/nats-server/v2/server.(*msgBlock).loadMsgsWithLock(0xc0002e01a0)
        github.com/nats-io/nats-server/v2/server/filestore.go:5299 +0x489
github.com/nats-io/nats-server/v2/server.(*msgBlock).firstMatching(0xc0002e01a0, {0xc001da2b80, 0x1c}, 0x1, 0x1, 0xc00022a650)
        github.com/nats-io/nats-server/v2/server/filestore.go:2128 +0x175
github.com/nats-io/nats-server/v2/server.(*fileStore).LoadNextMsg(0xc0002d8000, {0xc001da2b80, 0x1c}, 0x0?, 0xc004700aa8?, 0x44a9e6?)
        github.com/nats-io/nats-server/v2/server/filestore.go:5717 +0x24d
github.com/nats-io/nats-server/v2/server.(*consumer).getNextMsg(0xc002e37400)
        github.com/nats-io/nats-server/v2/server/consumer.go:3467 +0x766
github.com/nats-io/nats-server/v2/server.(*consumer).loopAndGatherMsgs(0xc002e37400, 0xc0045f2cc0)
        github.com/nats-io/nats-server/v2/server/consumer.go:3878 +0x2f9
github.com/nats-io/nats-server/v2/server.(*consumer).setLeader.func2()
        github.com/nats-io/nats-server/v2/server/consumer.go:1283 +0x54
created by github.com/nats-io/nats-server/v2/server.(*consumer).setLeader in goroutine 21
        github.com/nats-io/nats-server/v2/server/consumer.go:1281 +0xdcb
```

### Expected behavior

The expected behavior is to run and accept connections

### Server and client version

```
kubectl exec -it nats-0 -n nats -- nats-server --version
Defaulted container "nats" out of: nats, reloader
nats-server: v2.10.4
```

```
kubectl -n nats exec -i deploy/nats-box -- nats --version
v0.1.1
```

### Host environment

K8 VERSION : v1.21.14
OS IMAGE : CentOS Linux 7 (Core)
CONTAINER-RUNTIME : Docker

### Steps to reproduce

We are running a StatefulSet configuration with three replicas for our NATS setup. While the instances nats-0 and nats-1 are functioning properly, we are encountering issues with nats-2. This particular replica has entered a crash loop and has not recovered. Each replica in the setup uses Rook-Ceph storage, with a Persistent Volume Claim (PVC) individually bound to each.

**Comment by derekcollison** [comment]
Known bug, fixed in subsequent path release. We recommend upgrading to the latest which is 2.10.7 atm.
