### ISSUE TITLE
TLS handshake errors on nats container in K8

### ISSUE THREAD

**Issue by amit12cool** [nats-io/nats-server#5124]
### Observed behavior

I have a publisher publishing message to NATS server. The publisher is an Azure function publishing messages at regular intervals. 

```
I see the errors on the publisher:-

2024-02-23T18:10:33.016Z] nats: encountered error
Traceback (most recent call last):
  File "C:\Users\abcd\Code\Veli-IoT-System\message-ingestor\.venv\lib\site-packages\nats\aio\client.py", line 714, in _close
    await self._transport.wait_closed()
  File "C:\Users\abcd\Code\Veli-IoT-System\message-ingestor\.venv\lib\site-packages\nats\aio\transport.py", line 180, in wait_closed
    return await self._io_writer.wait_closed()
  File "C:\Users\abcd\AppData\Local\Programs\Python\Python39\lib\asyncio\streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "C:\Users\abcd\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\abcd\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 206, in feed_ssldata
    self._sslobj.unwrap()
  File "C:\Users\abcd\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 949, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2756)

```
I see errors in nats(server) containers as below
```
[7] 2024/02/23 18:14:27.845444 [ERR] 10.240.0.10:29783 - cid:206 - TLS handshake error: read tcp 10.244.6.44:4222->10.240.0.10:29783: i/o timeout
2/23/2024, 11:44:28 PM
nats-2
d13670d74711ba3ebf50e939852eb2efdc7dbe6010bb37abd81dcf8f7f2e8542
[7] 2024/02/23 18:14:28.144152 [ERR] 10.240.0.10:29783 - cid:206 - TLS handshake timeout
[7] 2024/02/23 18:14:28.806477 [ERR] 10.240.0.12:39668 - cid:207 - TLS handshake error: read tcp 10.244.6.44:4222->10.240.0.12:39668: i/o timeout
2/23/2024, 11:44:31 PM
nats-2
d13670d74711ba3ebf50e939852eb2efdc7dbe6010bb37abd81dcf8f7f2e8542
[7] 2024/02/23 18:14:31.045227 [ERR] 10.240.0.14:17010 - cid:208 - TLS handshake error: read tcp 10.244.6.44:4222->10.240.0.14:17010: i/o timeout
```

### Expected behavior

No TLS errors should be there.

### Server and client version

NATS version - 2.10.4-alpine
Client -> nats-py==2.6.0

### Host environment

K8's

### Steps to reproduce

TLS auth

**Comment by wallyqs** [comment]
I think you may have to bump the default `tls { timeout = X }` and `authorization { timeout = X }` for your deployment, have you tried tuning those?

**Comment by amit12cool** [comment]
@wallyqs  where can I bump this in the https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml helm chart.

**Comment by amit12cool** [comment]
@wallyqs with timeout = 50 in `tls` the timeout error was removed. But I see tls handhsake errors like below

```
[7] 2024/03/12 17:40:23.567594 [ERR] 10.240.0.4:59217 - cid:44 - TLS handshake error: read tcp 10.244.2.14:4222->10.240.0.4:59217: read: connection reset by peer
```

Points to note:-

- I have no client connected to the nats server i.e. any of the nats POD in k8
-  `10.244.2.14:4222` I know this is my nats pod server ip. But I don't know whose Ip is this `0.240.0.4:59217`. any idea, with whom the tcp connection is being made from bats server?

**Comment by amit12cool** [comment]
@neilalexander  @wallyqs please check above. This is critical for me.
